<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_abogados  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		/*
    $url = 'https://sigobwebcsj.ramajudicial.gov.co/TEST/wsAPICorrespondencia/srvAPICorrespondencia.asmx/ObtenerDespachosActivos';
    $data = array(
        'Contrasena' => '448B8890',
				 'Area' => ''
        // ... Agrega más parámetros según sea necesario
    );

    // Convertir los datos a formato de cadena
    $postData = http_build_query($data);

    // Configurar opciones de cURL
    $options = array(
        CURLOPT_URL            => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $postData,
    );

    // Inicializar cURL y configurar opciones
    $curl = curl_init();
    curl_setopt_array($curl, $options);
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);

    // Realizar la solicitud cURL y obtener la respuesta
    $response = curl_exec($curl);
    // Verificar errores
    if (curl_errno($curl)) {
        echo 'Error al realizar la solicitud: ' . curl_error($curl);
    }
		var_dump($response);
		$paginas = explode("\f", $response);
		//print_r($response);
		//echo "Numero de Despachos".count($response);
		//print_r($paginas);
		echo $paginas[0];
		//echo "<br>";
		//echo $paginas[1];
		//$result["total"]=$response;
    // Cerrar la sesión cURL
    curl_close($curl);
// Place event code here.
// Use "Add Action" button to add code snippets.
*/
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>