<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bdme_reporte_semestral_datachild  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

				
$_SESSION['ventanaWebpath'] = '/bdme_reporte_semestral_list.php';
set_time_limit(0); // Elimina la restricción de timeout
    // Verifica si hay un registro maestro disponible
    $data = $pageObject->getMasterRecord();

		
    
    if ($data) {
        // Obtiene el ID del sancionado
        $sancionadoId = $data["SancionadoId"];
        
        // Almacena el ID en la sesión
        $_SESSION['SancionadoIdData_report_Semestral'] = $sancionadoId;
    }

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		
		$sancionadoId = $_SESSION['SancionadoIdData_report_Semestral'];

    // Ejecutar la consulta
    $rs = CustomQuery("
				SELECT COUNT(ProcesoId) as TotalC6 FROM SancionadosPorProcesoView WHERE SancionadoId = $sancionadoId;
    ");



    while($record = db_fetch_array($rs)) {

        $tableHTML .= '<strong>' . htmlspecialchars($record['TotalC6']) . '</strong>';

    }

		
		// Ejecutar la consulta
$rs2 = CustomQuery("
    SELECT SUM(Obligacion + Costas + Intereses) as TotalC6 FROM SancionadosPorProcesoView WHERE SancionadoId = $sancionadoId;
");


// Verificar si se obtuvo un resultado
if ($record2 = db_fetch_array($rs2)) {

    // Formatear el número con puntos como separadores de miles
    $formattedValue = number_format($record2['TotalC6'], 0, '', '.');
    
    // Agregar el signo de pesos
    $formattedValueWithCurrency = "$" . $formattedValue;

    // Añadir el valor formateado a la tabla
    $tableHTML2 .= '<strong>' . htmlspecialchars($formattedValueWithCurrency) . '</strong>';

} else {
    // Manejar el caso donde no hay resultados
    $tableHTML2 .= '<strong>No se encontraron resultados</strong>';
}


    // Asignar el HTML generado al objeto xt
    $xt->assign("total_table", $tableHTML);
		$xt->assign("total_sum", $tableHTML2);





;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>