<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bdme_excluidos_datachild  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		
    // Verifica si hay un registro maestro disponible
    $data = $pageObject->getMasterRecord();
    
    if ($data) {
        // Obtiene el ID del sancionado
        $sancionadoId = $data["SancionadoId"];
        
        // Almacena el ID en la sesión
        $_SESSION['SancionadoIdDataExcluidos'] = $sancionadoId;
    }


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>