<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bdme_reporte_semestral_datachild  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

				set_time_limit(0); // Elimina la restricción de timeout
    // Verifica si hay un registro maestro disponible
    $data = $pageObject->getMasterRecord();
    
    if ($data) {
        // Obtiene el ID del sancionado
        $sancionadoId = $data["SancionadoId"];
        
        // Almacena el ID en la sesión
        $_SESSION['SancionadoIdData_report_Semestral'] = $sancionadoId;
    }

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>