<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bdme_incumplimiento_acuerdo_de_pago_semestral1  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

						//Obtener el primer día del mes actual: 
		$fecha1 = new DateTime();
		$fecha1->modify('first day of this month');
		//echo $fecha1->format('d/m/Y'); // imprime por ejemplo: 01/12/2012


    if(empty($_SESSION['mesIncumplimiento'])){
		
			$_SESSION['mesIncumplimiento'] = $fecha1->format('d/m/Y');

		}


set_time_limit(0); // Elimina la restricción de timeout
// Place event code here.
// Use "Add Action" button to add code snippets.

        // Obtener la URL completa de la página actual
    $currentUrl = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

    // Analizar la URL y obtener el path
    $parsedUrl = parse_url($currentUrl);
    $path = $parsedUrl['path'];
		 
    // Mostrar el path actual
    //echo "El path actual es: " . $path;

   if ($_SESSION['ventanaWebpath'] != $path) {
    $_SESSION['ventanaWebpath'] = $path;
    //unset($_SESSION['mesIncumplimiento']);
		}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>