<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bdme_publica  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		
$pageObject->hideItem("logo");



		set_time_limit(0); // Elimina la restricción de timeout

 	    // Obtener la URL completa de la página actual
    $currentUrl = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];

    // Analizar la URL y obtener el path
    $parsedUrl = parse_url($currentUrl);
    $path = $parsedUrl['path'];
		 
// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		
			$username = $_SESSION["UserNameF"];
			$Documento = $_SESSION['BDME_doc_sancionado_consulta'];
			global $xt;
			$fechActual = date('Y-m-d');

			$sql = " DECLARE @Documento VARCHAR(15)= '$Documento';
        DECLARE @Hasta DATE = EOMONTH(GetDate());
        DECLARE @Desde DATE = dateadd(day,1, DATEADD(month, -6, @Hasta));

		DECLARE @Fecha DATE = case when month(GetDate()) <= 5 then convert(date, convert(varchar,year(GetDate()))+'-05-31') else convert(date, convert(varchar,year(GetDate()))+'-11-30') end;

			SELECT TOP (1) 
				@Documento as Documento, 
				@Fecha as Fecha, 
			  ProcesosView1.Sancionado as Sancionado, 
				ProcesosView1.Seccional as Seccional, 
				ProcesosView1.SeccionalCorreo as Correo, 
				ProcesosView1.SeccionalDireccion as Direccion, 
				ProcesosView1.SeccionalTelefonos as Telefonos, 
				ProcesosView1.PiePagina as Pie
			FROM     ProcesosView1 CROSS JOIN
				Salarios
			WHERE  (ProcesosView1.EstadoId <> 6) 
				AND ((ProcesosView1.Acuerdo IS NULL) OR 
				(NOT ProcesosView1.Incumplimiento IS NULL)) 
				AND (ProcesosView1.Ejecutoria <= @Desde) 
				AND (ProcesosView1.Documento = @Documento) 
				AND (Salarios.Ano = YEAR(GETDATE()))
			group by
				ProcesosView1.Sancionado,
				ProcesosView1.Seccional, 
				ProcesosView1.SeccionalCorreo, 
				ProcesosView1.SeccionalDireccion, 
				ProcesosView1.SeccionalTelefonos, 
				ProcesosView1.PiePagina,
				Salarios.Salario
			having
				SUM(ROUND(Saldo, 0)) > dbo.Salarios.Salario * 5.0";
			$resultado = CustomQuery($sql);

			// Obtener el valor de reset_date
			if ($data = db_fetch_array($resultado)) {
				 $fecha = $data["Fecha"];
				 // Convertir la fecha
				 $fecha_formateada = date('j/n/Y', strtotime($fecha));
				 $sancionado = $data["Sancionado"];
				 $direccion = $data["Direccion"];
				 $seccional = $data["Seccional"];
				 $correo = $data["Correo"];
				 $telefono = $data["Telefonos"];
         $pie = $data["Pie"];
					$modalHTML = "
				 <tr class='k-detail-row'>
					  <td class='k-detail-cell visible' colspan='3' style='text-align: center;'>
							<p></p>
							<p><strong>Será reportado en el Boletín de Deudores Morosos del Estado con corte a $fecha_formateada, salvo que antes pague la totalidad de lo adeudado a la Rama Judicial o suscriba Acuerdo de Pago que deberá cumplir.</strong></p>
							<p></p>
							<p><strong>Para mayor información comuníquese con: $seccional</strong></p>
							<p></p>
							<p><strong>Dirección: $direccion</strong></p>
							<p><strong>Teléfonos: $telefono - Correo: $correo</strong></p>
							<p></p>
							<p>Esta consulta es informativa, no tiene costo y no es válida como recibo de pago ni Paz y Salvo</p>
					  </td>
				 </tr>
			";
			} else {

					if($Documento != ''){
				 	$modalHTML = "
				 <tr class='k-detail-row'>
					  <td class='k-detail-cell visible' colspan='3' style='text-align: center;'>
							<p></p>
							<p><strong>No es sujeto de reporte al Boletín de Deudores Morosos del Estado - BDME</strong></p>
							<p></p>
							<p>Esta consulta es informativa, no tiene costo y no es válida como recibo de pago ni Paz y Salvo</p>
					  </td>
				 </tr>";
				 }
			}




		 // Asignar el modal al template
		 $xt->assign("modalAlertaBDME", $modalHTML);
				
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>