<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_carceles  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowAdd"]=true;


		$this->events["BeforeShowEdit"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		
// Consulta SQL para obtener las nomenclaturas convertirá todos los valores de la columna Nomenclatura a mayúsculas
$sql = "SELECT Codigo, UPPER(Nomenclatura) AS Nomenclatura FROM Nomenclaturas ORDER BY Nomenclatura";

$qResult = CustomQuery($sql);

// Generar opciones HTML
$options = '<option value="">Seleccione...</option>';
while ($row = db_fetch_array($qResult)) {
    $options .= '<option value="' . $row["Codigo"] . '">' . $row["Nomenclatura"] . '</option>';
}

// Verifica si la variable tiene datos
/*echo "<pre>";
print_r($options);
echo "</pre>";
exit(); // Detiene la ejecución para ver la salida*/

	 

	 $xt->assign("direccion_form", file_get_contents("templates/fragmento_direccion.html"));
	 $xt->assign("direccion_form2", file_get_contents("templates/fragmento_direccion2.html"));

	 //$xt->assign("direccion_form", file_get_contents(getabspath("custom_files/fragmento_direccion.html")));
   //$xt->assign("direccion_form2", file_get_contents(getabspath("custom_files/fragmento_direccion2.html")));

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		
$sql = "SELECT Codigo, UPPER(Nomenclatura) AS Nomenclatura FROM Nomenclaturas ORDER BY Nomenclatura";

$qResult = CustomQuery($sql);

// Generar opciones HTML
$options = '<option value="">Seleccione...</option>';
while ($row = db_fetch_array($qResult)) {
    $options .= '<option value="' . $row["Codigo"] . '">' . $row["Nomenclatura"] . '</option>';
}

	 

	 $xt->assign("direccion_form", file_get_contents("templates/fragmento_direccion.html"));
	 $xt->assign("direccion_form2", file_get_contents("templates/fragmento_direccion2.html"));

	 //$xt->assign("nomenclaturas_options", $options);


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>