<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chequeos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["CustomAdd"]=true;

		$this->events["AfterAdd"]=true;



		$this->events["CustomEdit"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeQueryList"]=true;

		$this->events["BeforeDelete"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if ($data["Procesado"]==1){ 
  //$record["ChequeoId_css"].='background:yellow';
	$pageObject->hideItem("button_crear", $recordId);
	$pageObject->hideItem("grid_edit", $recordId);
	$pageObject->hideItem("grid_checkbox", $recordId);
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		unset($values["ObligacionLetras"]); //Se borran los campos que no existen en la tabla Chequeos
unset($values["CantidadLetras"]);
unset($values["Dias"]);
$values["Fecha"]=now();
//$values["Obligacion"]=$_SESSION["Obligacion"];
/*
foreach ($values as $value){
echo "Valorr de ".$values.": ".$value."<br>";
}
*/
//print_r($values);
//echo "valorrr de Obligacion: ".$values["Obligacion"];
//$values["Obligacion"]=$_SESSION["Obligacion"];
//echo "El valor issss: ".$_SESSION["Obligacion"];
// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
$consulta=DB::exec("declare @p2 int
set @p2=0
declare @p3 nvarchar(max)
set @p3=N''
exec [dbo].[Chequeos_Validar] @ChequeoId=".$values["ChequeoId"].",@Err_num=@p2 output,@Err_msg=@p3 output
select @p2 error_num, @p3 error-msg");

/*$consulta=DB::Query("SELECT Cierre FROM Empresas WHERE EmpresaId = 1");
        while($date=$consulta->fetchAssoc()){
                $fechaCierre=$date["Cierre"];
        }
*/

/*
echo "<script>var confirm1;
confirm1=confirm('EL REGISTRO FUE REALIZADO CON EXITO');
if(confirm1)
{
		//console.log ('ingresooo');
    //location.reload();
		//pageObj.reload({a:'reload'});
		//location.reload();
		//window.location.href ='http://localhost:8086/chequeos_list.php?a=reload&';
		//window.location.href = window.location.href;
		//window.location.href ='http://localhost:8086/chequeos_list.php?a=return&fly=1&';
		//window.location.href ='http://localhost:8086/chequeos_list.php';
}</script>"
*/
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		unset($values["ObligacionLetras"]); //Se borran los campos que no existen en la tabla Chequeos
unset($values["CantidadLetras"]);
unset($values["Dias"]);
$values["Fecha"]=now();
$values["Obligacion"]=floatval($values["Obligacion"]);

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		//$pageObject->setProxyValue('saved', true);  
//$pageObject->stopPRG = true;
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		//echo "Value del campo: ".$recordId;
// Place event code here.
// Use "Add Action" button to add code snippets.
$values["Obligacion"]=$_SESSION["Obligacion"];
$values["Remisorio"]=mb_strtoupper($values["Remisorio"], 'UTF-8');
//print_r($values);

$length=mb_strlen($values["Origen"], 'UTF-8');
if ($length<23||$length>23){
	echo '<script>alert ("El numero de Origen debe contener 23 caracteres ")</script>';
	return false;
}
elseif($values['Ejecutoria']<$values['Providencia']){
	echo '<script>alert ("La Fecha Ejecutoria: '.$values['Ejecutoria'].' debe ser mayor o igual a la Fecha Providencia: '.$values['Providencia'].'")</script>';
	return false;
}
elseif($values['Ejecutoria']>$values['Plazo']){
	echo '<script>alert ("La Fecha Ejecutoria: '.$values['Ejecutoria'].' debe ser menor o igual a la Fecha Plazo: '.$values['Plazo'].'")</script>';
	return false;
}
elseif($values['FechaSancion']>now()){
	echo '<script>alert ("La Fecha Sancion: '.$values['FechaSancion'].' debe ser menor o igual a la Fecha Actual: '.now().'")</script>';
	return false;
}
return true;


;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$strWhereClause = whereAdd($strWhereClause, "SeccionalId in (".$_SESSION["Seccionales"].")");


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, $pageObject)
{

		DB::Delete("ChequeosSancionados", "ChequeoId=".$deleted_values["ChequeoId"]."" );
DB::Delete("Devoluciones", "ChequeoId=".$deleted_values["ChequeoId"]."" );
DB::Delete("ChequeosOficios", "ChequeoId=".$deleted_values["ChequeoId"]."" );

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		//print_r($values);
$values["Remisorio"]=mb_strtoupper($values["Remisorio"], 'UTF-8');
//$values["Obligacion"]=$_SESSION["Obligacion"];
//echo $_SESSION["Obligacion"];

if ($_SESSION["Obligacion"]!=NULL){
	$values["Obligacion"]=$_SESSION["Obligacion"];
}

//print_r($values);

$length=mb_strlen($values["Origen"], 'UTF-8');
if ($length<23||$length>23){
	echo '<script>alert ("El numero de Origen debe contener 23 caracteres ")</script>';
	return false;
}
elseif($values['Ejecutoria']<$values['Providencia']){
	echo '<script>alert ("La Fecha Ejecutoria: '.$values['Ejecutoria'].' debe ser mayor o igual a la Fecha Providencia: '.$values['Providencia'].'")</script>';
	return false;
}
elseif($values['Ejecutoria']>$values['Plazo']){
	echo '<script>alert ("La Fecha Ejecutoria: '.$values['Ejecutoria'].' debe ser menor o igual a la Fecha Plazo: '.$values['Plazo'].'")</script>';
	return false;
}
elseif($values['FechaSancion']>now()){
	echo '<script>alert ("La Fecha Sancion: '.$values['FechaSancion'].' debe ser menor o igual a la Fecha Actual: '.now().'")</script>';
	return false;
}
return true;
;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>