<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chequeossancionados  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		 // Validar que solo contenga letras
 if (!preg_match('/^[a-zA-Z\s]+$/', $values['Sancionado'])) {
	  echo "<script>alert('El nombre del Sancionado no debe contener numeros, ni caracteres especiales ni tíldes.');</script>";
		return false;
 }
if ($values['TipoDocumentoId']==2 || $values['TipoDocumentoId']==1){

	if (!ctype_digit($values['Documento'])) {
		 echo "<script>alert('El Documento tipo Cédula de Ciudadanía y Tarjeta de Identidad deben ser numericos.');</script>";
		 return false;
	}
}

return true;

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		 // Validar que solo contenga letras
 if (!preg_match('/^[a-zA-Z\s]+$/', $values['Sancionado'])) {
	  echo "<script>alert('El nombre del Sancionado no debe contener numeros, ni caracteres especiales ni tíldes.');</script>";
		return false;
 }
if ($values['TipoDocumentoId']==2 || $values['TipoDocumentoId']==1){

	if (!ctype_digit($values['Documento'])) {
		 echo "<script>alert('El Documento tipo Cédula de Ciudadanía y Tarjeta de Identidad deben ser numericos.');</script>";
		 return false;
	}
}

return true;

;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>