<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chequeos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["CustomAdd"]=true;

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if ($data["Procesado"]==1){ 
  //$record["ChequeoId_css"].='background:yellow';
	$pageObject->hideItem("button_crear", $recordId);
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		unset($values["ObligacionLetras"]); //Se borran los campos que no existen en la tabla Chequeos
unset($values["CantidadLetras"]);
$values["Fecha"]=now();

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		 // Verifica si la inserción fue exitosa
    if ($pageObject->status == "success") {
        // Genera código JavaScript para mostrar un SweetAlert
				echo '<script>alert("FINISHHHHHH:");</script>';
        $jsCode = "
            <script>
                swal({
                    title: 'Registro exitoso',
                    text: 'El registro se ha agregado satisfactoriamente.',
                    icon: 'success',
                    confirmButtonText: 'Aceptar'
                });
            </script>
        ";
        
        // Imprime el código JavaScript
        echo $jsCode;
    }

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>