<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chequeosoficios  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;


		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		$values["Fecha"]=now();
// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		// Place event code here.
// Use "Add Action" button to add code snippets.
include_once (getabspath("plantillaGCC.php"));
global $pageObject;
$data = $pageObject->getMasterRecord();
//echo "El AbogadoId del proceso es: ".$data["AbogadoId"];
if($data["AbogadoId"]==$_SESSION["AbogadoId"]){
//SE OBTIENEN LA VARIABLES PARA CONUSMIR LOS METODOS DE LA API SIGOBIUS
$consulta = DB::Query("SELECT Despacho,Codificador FROM Abogados where AbogadoId=(SELECT AbogadoId from Chequeos where ChequeoId=".$values["ChequeoId"].")");
        //$consulta="SELECT * from Tasas where Desde like '%".$a."-".$m."%' and Tipo=1";
            while($date=$consulta->fetchAssoc()){
            $despacho=$date["Despacho"];
            $codificador=$date["Codificador"];
            //echo "La tasa de Usura diaria es: ".$tasaUsuraDiaria."<br>";
        };
$consulta=DB::Query("SELECT  D.Despacho AS 'Despacho', 
        Juez AS 'DespachoJuez',
        Direccion AS 'DespachoDireccion',
        Correo AS 'DespachoCorreo',
        IIF (D.juez=null,'Doctor','Doctora') AS 'Doctor'
        FROM Despachos D
        INNER JOIN Chequeos C ON C.DespachoId = D.DespachoId
        WHERE ChequeoId =".$values["ChequeoId"]."");
        while( $date = $consulta->fetchAssoc() )
				{
            $despachoJuez=$date["DespachoJuez"];
        }
$consulta=DB::Query("SELECT * FROM Oficios WHERE OficioId=".$values["OficioId"]."");
        while( $date = $consulta->fetchAssoc() )
				{
            $asunto=$date["Oficio"];
        }
//CONSUMINOS EL METODO DE NuevaCorrespondencia de la API SOAP
//la url de la conexion a Sigob
$url = 'https://sigobwebcsj.ramajudicial.gov.co/TEST/wsAPICorrespondencia/srvAPICorrespondencia.asmx/NuevaCorrespondencia';
//Parametro a enviar para consumir el metodo
$data = array(
    'Despacho' => $despacho,
    'Codificador' => $codificador,
    'SoloEditorExterno' => '1',
    'Contrasena' => '448B8890'
    // ... Agrega más parámetros según sea necesario
);

// Convertir los datos a formato de cadena
$postData = http_build_query($data);

// Configurar opciones de cURL
$options = array(
    CURLOPT_URL            => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST           => true,
    CURLOPT_POSTFIELDS     => $postData,
);

// Inicializar cURL y configurar opciones
$curl = curl_init();
curl_setopt_array($curl, $options);

//NO VALIDAR SI REQUIERE SSL
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);

// Realizar la solicitud cURL y obtener la respuesta
$response2 = curl_exec($curl);
// Verificar errores
if (curl_errno($curl)) {
    echo 'Error al realizar la solicitud: ' . curl_error($curl);
		return false;
}else{
// Imprimir la respuesta del servicio web
//echo "<br>Valor del metodo NuevaCorrespondencia: ".$response2."<br>";
$xml = new SimpleXMLElement($response2);
$radicadoF=strval($xml[0]);
$_SESSION["Radicado"]=$radicadoF;
////////
//CONSUMINOS EL METODO DE ActualizarCorrespondencia de la API SOAP
$curl = curl_init();
//Juannnnnnnn
//SE LLAMA LA FUNCION LA CUAL TOMA LA PLANTILLA Y REEMPLAZA SUS VARIABLES, CREANDO UN NUEVO .DOCX
 $objeto=new plantillaDev($values["ChequeoId"],$values["OficioId"],$radicadoF);
 $objeto->funcGlobal();
//$rutaArchivo = 'Plantilla_1097.docx';
$rutaArchivo = 'templates_GCC/Archivo_'.$values["ChequeoId"].'_'.$values["OficioId"].'.docx';
// Leer el contenido del archivo como un arreglo de bytes
$bytesDocumento = file_get_contents($rutaArchivo);
$base64 = base64_encode($bytesDocumento);
//echo "Valor de base64: ".$base64;
//echo $base64;
//$radicado='DEAJGCC23-12554';
//echo "<br>valor del string quemando ekl radicado DEAJ-XXXX: ".var_dump($radicado);
//echo $bytesDocumento;
//$bytesDocumento =  unpack("C*", $bytesDocumento);
//$radicado='DEAJGCC23-12547';
//print_r($bytesDocumento);

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://sigobwebcsj.ramajudicial.gov.co/TEST/wsAPICorrespondencia/srvAPICorrespondencia.asmx',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <ActualizarCorrespondencia xmlns="http://tempuri.org/">
      <CodigoRegistro>'.$radicadoF.'</CodigoRegistro>
      <Asunto>'.$asunto.'</Asunto>
      <Tipo>2</Tipo>
      <GradoReserva>0</GradoReserva>
      <Prioridad>0</Prioridad>
      <MedioEnvio>0</MedioEnvio>
      <EsperaRespuesta>N</EsperaRespuesta>
      <FechaEstimadaRespuesta>'.now().'</FechaEstimadaRespuesta>
      <ResultadoGestion>-1</ResultadoGestion>
      <Objetivos>11</Objetivos>
      <FormatoDocumento>1</FormatoDocumento>
      <Documento>'.$base64.'</Documento>
      <NombreDocumento>Prueba wsAPICorrespondencia.docx</NombreDocumento>
      <DocumentoTexto>Texto sin formato del documento</DocumentoTexto>
      <Firmante>'.$despacho.'</Firmante>
      <Estado>0</Estado>
      <DespachoDestino></DespachoDestino>
      <Vocativo>-1</Vocativo>
      <Apellido>'.$despachoJuez.'</Apellido>
      <Nombre>'.$despachoJuez.'</Nombre>
      <NumeroDocumento>12345</NumeroDocumento>
      <Sexo>0</Sexo>
      <FechaNacimiento>1977/01/01</FechaNacimiento>
      <Institucion>-1</Institucion>
      <Cargo>-1</Cargo>
      <Departamento>-1</Departamento>
      <Telefono>09811111231</Telefono>
      <CorreoElectronico>alelamonaca@gmail.com</CorreoElectronico>
      <Calle>Mi calle</Calle>
      <Ciudad>Asunción</Ciudad>
      <ProvinciaDepartamento>Central</ProvinciaDepartamento>
      <Pais>Paraguay</Pais>
      <TipoDireccion>1</TipoDireccion>
      <CodigoRegistroPrecedente></CodigoRegistroPrecedente>
      <EsRespuesta>0</EsRespuesta>
      <Contrasena>448B8890</Contrasena>
    </ActualizarCorrespondencia>
  </soap12:Body>
</soap12:Envelope>',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: text/xml',
    'Cookie: ASP.NET_SessionId=4uvpkyerhy21mcwghvyqfuw0'
  ),
));

//NO VERIFICAR CERTICADO SSL
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);

$response = curl_exec($curl);
//echo '<br>Respuesta de la API Metodo Actualizar Correspondencia: ' . $response;
$xml = new SimpleXMLElement($response);
    // Definir el namespace
    $namespaces = $xml->getNamespaces(true);
    $soapNamespace = $namespaces['soap'];

    // Acceder al cuerpo del SOAP
    $body = $xml->children($soapNamespace)->Body;

    // Acceder al namespace específico del cuerpo
    $responseNamespace = $namespaces[''];
    $token = $body->children($responseNamespace)->ActualizarCorrespondenciaResponse->ActualizarCorrespondenciaResult;
		$token=strval($token);
		$_SESSION["token"]=$token;
    // Mostrar el resultado
    //echo "Resultado: " .$token;
		//var_dump($token);
if ($response == false) {
    echo 'Error en la solicitud cURL: ' . curl_error($curl);
		return false;
} else {
		//echo "Result: ".$token ;
		$ultimosCaracteres = substr($token, -2);
    
    // Comparar con "=="
    if ($ultimosCaracteres === "==") {
				curl_close($curl);
        return true;
    } else {
				 echo "<script>alert('El codigo obtenido es el: ".$radicadoF." y se presento un error: ".$token.", solucionarlo o de no ser solucionable, intentelo mas tarde')</script>";
        return false;
    }
}
}
}
  else{
	echo "<script>alert('El Despacho resgistrador no esta autorizado a indicar como firmante al despacho firmante')</script>";
	return false;
}
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		//echo "Values del Radicado: ".$_SESSION["Radicado"];
//echo "<br>Valor del Token: ".$_SESSION["token"];
//$GLOBALS["radicadoF"];
$resultado["response"]=DB::Exec("UPDATE ChequeosOficios set Radicado='".$_SESSION["Radicado"]."',Codigo='".$_SESSION["token"]."' where ChequeoOficioId=".$values['ChequeoOficioId']."");
                    if (!$resultado["response"]){
                        echo "Ocurrio un error debido a: ".DB::LastError(); 
                        return false;
                    } 
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>