<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_consolidado_por_conceptos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		
		$U_user = $_SESSION["UserNameF"];
		 $id_user = $_SESSION['consolidado_UserId'];
		 $cons_cartera = $_SESSION['consolidado_cartera'];
		 $cons_mes = $_SESSION['consolidado_mes'];// Fecha en formato YYYY-MM-DD

		 // Separar la fecha en año, mes y día
		//list($ano, $mes, $dia) = explode('-', $cons_mes);

				// Crear un objeto DateTime a partir del año y mes
		$date = new DateTime($cons_mes);

		// Establecer el último día del mes usando el método modify
		$date->modify('last day of this month');

		// Separar el año, mes y el último día
		$ano = $date->format('Y');
		$mes = $date->format('m');
		$dia = $date->format('d'); // Último día del mes

		// Definir un array con los nombres de los meses
		$meses = [
			 '01' => 'enero',
			 '02' => 'febrero',
			 '03' => 'marzo',
			 '04' => 'abril',
			 '05' => 'mayo',
			 '06' => 'junio',
			 '07' => 'julio',
			 '08' => 'agosto',
			 '09' => 'septiembre',
			 '10' => 'octubre',
			 '11' => 'noviembre',
			 '12' => 'diciembre'
		];

		// Convertir el mes numérico al nombre correspondiente
		$nombre_mes = $meses[$mes];

		// Definir un array con los nombres de las carteras
		$cartera = [
			 '1' => 'CARTERA CORRIENTE',
			 '2' => 'CARTERA PRESCRITA CSJ',
			 '3' => 'CARTERA PRESCRITA MINJUSTICIA',
			 '4' => 'CARTERA MINJUSTICIA',
			 '5' => 'CARTERA EJEMPLARIZANTE'
		];

		// Convertir el id cartera numérico al nombre correspondiente
		$cartera_nombre = $cartera[$cons_cartera];


		global $xt;  // Usa $xt para asignar el valor a la plantilla

		// Sanitizar el valor para evitar inyecciones SQL
		$IdValue = addslashes($U_user);

		// Crear y ejecutar la consulta SQL
		$sql = "DECLARE @Millones INT = 0; 	
							DECLARE @Divisor INT = CASE 
										WHEN @Millones = 1
											THEN 1e6
										ELSE 1
										END;
								DECLARE @UserId INT = '$id_user';
								DECLARE @CarteraTipoId INT = '$cons_cartera';
								DECLARE @Desde DATE = '$cons_mes';
								DECLARE @Hasta DATE = dateadd(day, - 1, dateadd(month, 1, @Desde));

								IF @Desde < Convert(DATE, '01/01/2015', 103)
									SET @Desde = Convert(DATE, '01/01/1930', 103)

								SELECT @Hasta AS Hasta
									,Seccionales.Seccional
									,ROUND(isnull(SUM(CASE 
												WHEN Resumen.ConceptoId = 1
													THEN Resumen.ObliTota
												END) / @divisor, 0),0) AS MultTota
									,ROUND(isnull(SUM(CASE 
												WHEN Resumen.ConceptoId = 1 
													THEN Resumen.InteTota + Resumen.CostTota
												END) / @divisor, 0),0) AS InteTota
									,ROUND(isnull(SUM(CASE 
												WHEN Resumen.ConceptoId = 5
													THEN Resumen.ObliTota + Resumen.InteTota + Resumen.CostTota
												END) / @divisor, 0),0) AS IncaTota
									,ROUND(isnull(SUM(CASE 
												WHEN Resumen.ConceptoId = 4 
													THEN Resumen.ObliTota + Resumen.InteTota + Resumen.CostTota
												END) / @divisor, 0),0) AS OtroTota
									,CarteraTipos.CarteraTipo
									,SUM(Resumen.ProcTota) AS ProcTota
								FROM Resumen
								INNER JOIN Seccionales ON Resumen.SeccionalId = Seccionales.SeccionalId
								INNER JOIN CarteraTipos ON Resumen.CarteraTipoId = CarteraTipos.CarteraTipoId
								WHERE (Resumen.CarteraTipoId = @CarteraTipoId)
									AND (Resumen.Hasta = @Hasta)
								GROUP BY Seccionales.Seccional
									,CarteraTipos.CarteraTipo";
		    // Define tu consulta SQL

    // Ejecuta la consulta
    $resultado = CustomQuery($sql);

		// Genera el inicio de la tabla HTML
		$htmlTable = '<div id="miContenedor" style="display: flex; margin-bottom: 20px;">';

		// Agrega el texto
		//$htmlTable .= '<div style="flex: 1; text-align: center; font-weight: bold; font-size: 16px;">';
		$htmlTable .= '<div style="flex: 1;">';
				// Agrega la imagen
		//$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px;">';
		$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px; float: left; margin-right: 20px;">';
		$htmlTable .= '<p style="display: block; text-align: center; font-weight: bold; font-size: 16px; margin-left: 235px;">';
		$htmlTable .= 'Dirección Ejecutiva de Administración Judicial<br>';
		$htmlTable .= 'Con corte al '.$dia.' de '.$nombre_mes.' de '.$ano.'<br>';
		$htmlTable .= ''.$cartera_nombre.'';
		$htmlTable .= '</p>';




		// Agrega el título de la tabla
		$htmlTable .= '<table border="1" cellpadding="5" cellspacing="0" style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;">';

		// Estilo de encabezado
		$htmlTable .= '<thead style="background-color: #d9d9d9; font-weight: bold; text-align: center;">';
		$htmlTable .= '<tr>';
		$htmlTable .= '<td colspan="7" style="text-align: center; font-weight: bold; font-size: 18px; background-color: #d9d9d9;">CONSOLIDADO POR CONCEPTOS</td>';
		$htmlTable .= '</tr>';
		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Dirección Seccional</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">1.3.11.02 Multas</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">1.3.11.03 Intereses y Costas de Multas</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">1.3.84.26 Incapacidades</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">1.3.84.90 Otros Deudores   -Reintegros-</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Número de Procesos</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Total Cobro Coactivo</th>';
		$htmlTable .= '</tr>';
		$htmlTable .= '</thead>';

		// Genera el cuerpo de la tabla
		$htmlTable .= '<tbody>';

		// Procesa los resultados y agrega las filas
		while ($data = db_fetch_array($resultado)) {

			  // Calcula la suma de los totales
			 $totalSuma = $data['MultTota'] + $data['InteTota'] + $data['IncaTota'] + $data['OtroTota'];
			 $totalMulta = $totalMulta + $data['MultTota'];
			 $totalIntere = $totalIntere + $data['InteTota'];
			 $totalIncapac = $totalIncapac + $data['IncaTota'];
			 $totalOtros = $totalOtros + $data['OtroTota'];
			 $totalProcTota = $totalProcTota + $data['ProcTota'];
			 $totalCobro = $totalCobro + $totalSuma;

			 $htmlTable .= '<tr>';
			 $htmlTable .= '<td style="text-align: left;">' . htmlspecialchars($data['Seccional']) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['MultTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['InteTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['IncaTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['OtroTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($totalSuma, 0, ',', '.')) . '</td>'; // Nueva columna para la suma
			 $htmlTable .= '</tr>';

				
		}
		
		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; font-weight: bold;">TOTAL</th>';
		
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalMulta, 0, ',', '.').'</th>';
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalIntere, 0, ',', '.').'</th>';
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalIncapac, 0, ',', '.').'</th>';
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalOtros, 0, ',', '.').'</th>';
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalProcTota, 0, ',', '.').'</th>';
		$htmlTable .= '<th font-weight: bold; style="text-align: right;">'.number_format($totalCobro, 0, ',', '.').'</th>';
		$htmlTable .= '</tr >';


		$htmlTable .= '</tbody>';
		$htmlTable .= '</table>';
		$htmlTable .= '</div>';
		$htmlTable .= '</div>'; // Cierra el div flex


		// Asigna el HTML generado a una variable para usarla en la plantilla
		$xt->assign("mi_tabla_html", $htmlTable);

		return true; // Devuelve true para continuar con el proceso

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>