<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_correspondencias  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;


		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		$values["UserId"]=$_SESSION["UserId"];
/*
include_once (getabspath("classes/actuacionAction.php"));
$oficioId=$values["OficioId"];
$fechaLiqui=date("d-m-Y");
$fechaAct=date('Y-m-d H-i-s');
//print_r($values);
//echo $oficioId;
if ($oficioId==1097){
		//echo "Entrooooo";
		//$actuacionId=4; //PERSUASIVO
		$response=DB::Query("SELECT ActuacionId FROM Oficios WHERE OficioId=".$oficioId);
		//print_r($actuacionId);
		while( $date = $response->fetchAssoc() )
				{
					$actuacionId=$date["ActuacionId"];
				}
		$recalcular=new reliquidacion($values["ProcesoId"]);
		$meses = $recalcular->Calcular();
		$result["total"]=$recalcular->getInteresesSuma();
		//$result["total"]=$recalcular->getSuma();
		$resultado["response"]=DB::Exec("UPDATE Procesos set Intereses=".$result["total"].",InteresesInicial=".$result["total"].",Liquidacion='".$fechaLiqui."',SeleccionadoFecha=".$fechaLiqui.", Persuasivo='".$fechaLiqui."',ActuacionId=".$actuacionId." where ProcesoId=".$values["ProcesoId"]);
		$resultado2["response"]=DB::Exec("INSERT INTO Intereses (ProcesoId,Fecha,Intereses,SeccionalId,Liquidacion,PagoId) values (".$values["ProcesoId"].",'".$values["Fecha"]."',".$result["total"].",NULL,0,NULL)");
		if ($resultado2["response"] && $resultado["response"]) {
            echo '<script>alert("Se agrega la correspondencia PERSUASIVO y se calculan los intereses a la fecha")</script>';
        }
        else {
            // Hubo un error en la ejecución de la consulta
							echo "Ocurrio un error".DB::LastError();
            //echo "<script>alert("Se realiza la actualizacion del pagoId")</script>Error al ejecutar la consulta: " . DB::LastError();
            //exit();
        }
}



// Place event code here.
// Use "Add Action" button to add code snippets.
*/
return true;

;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		include_once (getabspath("classes/actuacionAction.php"));
include_once (getabspath("classes/pruebaJuan.php"));
$oficioId=$values["OficioId"];
//$fechaLiqui=date("d-m-Y");
//$fechaAct=date('Y-m-d H-i-s');
$response=DB::Query("SELECT ActuacionId FROM Oficios WHERE OficioId=".$oficioId);
		//print_r($actuacionId);
		while( $date = $response->fetchAssoc() )
				{
					$actuacionId=$date["ActuacionId"];
				}
$response=DB::Query("SELECT EtapaId FROM Actuaciones WHERE ActuacionId=".$actuacionId);
		//print_r($actuacionId);
		while( $date = $response->fetchAssoc() )
				{
					$etapaId=$date["EtapaId"];
				}
$oficio=new coreOficios($actuacionId,$values["ProcesoId"],$values["Fecha"],$values["Resolucion"],$values["Radicado"],$values["Observaciones"],$values["UserId"],$etapaId);
$response=$oficio->process();
if ($response==true){
	echo '<script>alert("Se agrega la correspondencia correctamente")</script>';
	return true;
}
else{
	return false;
}

// Place event code here.
// Use "Add Action" button to add code snippets.


;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>