<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_gesti_n_medidas_cautelares  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

				  global $xt;

			$Gestion_Medidas_mes = $_SESSION['Gestion_medidas'];
			$dateHasta = new DateTime($Gestion_Medidas_mes);
			$ultimo_dia = $dateHasta->modify('last day of this month')->format('d-m-Y');


  		$sql = "    DECLARE @Hasta DATE = '$Gestion_Medidas_mes';
	 DECLARE @Desde DATE;
	 SET @Hasta = EOMONTH(@Hasta);
	 SET @Desde = DATEADD(MONTH, -2, DATEADD(MONTH, DATEDIFF(MONTH, 0, @Hasta), 0));
     WITH a
          AS (
          -- 1 Inicial
          SELECT SeccionalId, 
                 COUNT(*) AS ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
                Hasta = @Hasta
               AND CarteraTipoId = 1
          GROUP BY SeccionalId

          UNION ALL -- 4 Inicial

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 COUNT(*) AS ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
               Hasta = @Hasta
               AND CarteraTipoId = 4
          GROUP BY SeccionalId

          UNION ALL -- 5 Inicial

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 COUNT(*) AS ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
               Hasta = @Hasta
               AND CarteraTipoId = 5
          GROUP BY SeccionalId

          UNION ALL -- 1 Final

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 COUNT(*) AS ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 1)
			   --AND (EstadoId = 2)
                   AND EXISTS
              (
				SELECT        ProcesoId
				FROM            Correspondencias
				WHERE        (ProcesoId = Historicos.ProcesoId and OficioId in (1121,1131,4347,4359,4437,4548,4638) and Fecha between @Desde and @Hasta)
              )
          GROUP BY SeccionalId

          UNION ALL -- 4

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 COUNT(*) AS ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 4)
			   --AND (EstadoId = 2)
                   AND EXISTS
              (
				SELECT        ProcesoId
				FROM            Correspondencias
				WHERE        (ProcesoId = Historicos.ProcesoId and OficioId in (1121,1131,4347,4359,4437,4548,4638) and Fecha between @Desde and @Hasta)
              )
          GROUP BY SeccionalId

          UNION ALL -- 5 Final

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 COUNT(*) AS ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 5)
			   --AND (EstadoId = 2)
                   AND EXISTS
              (
				SELECT        ProcesoId
				FROM            Correspondencias
				WHERE        (ProcesoId = Historicos.ProcesoId and OficioId in (1121,1131,4347,4359,4437,4548, 4638) and Fecha between @Desde and @Hasta)
              )
          GROUP BY SeccionalId
		  )
          SELECT Seccional, 
                 SUM(a.ProcInic1) ProcInic1, 
				 SUM(a.ProcInic1*0.2) ProcInic120, 
                 SUM(a.ProcInic4) ProcInic4, 
				 SUM(a.ProcInic4*0.2) ProcInic420, 
                 SUM(a.ProcInic5) ProcInic5, 
				 SUM(a.ProcInic5*0.2) ProcInic520,
                 SUM(a.ProcInic1) + SUM(a.ProcInic4) + SUM(a.ProcInic5) ProcInicTota, 
				 (SUM(a.ProcInic1) + SUM(a.ProcInic4) + SUM(a.ProcInic5))*0.2 ProcInicTota20, 
                 SUM(a.ProcFina1) ProcFina1, 
                 SUM(a.ProcFina4) ProcFina4, 
                 SUM(a.ProcFina5) ProcFina5, 
                 SUM(a.ProcFina1) + SUM(a.ProcFina4) + SUM(a.ProcFina5) ProcFinaTota,
                 CASE
                     WHEN CONVERT(DECIMAL, (SUM(a.ProcInic1*0.2))) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina1))) / CONVERT(DECIMAL, (SUM(a.ProcInic1*0.2)))
                 END ProcIndi1,
                 CASE
                     WHEN CONVERT(DECIMAL, (SUM(a.ProcInic4*0.2))) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina4))) / CONVERT(DECIMAL, (SUM(a.ProcInic4*0.2)))
                 END ProcIndi4,
                 CASE
                     WHEN CONVERT(DECIMAL, (SUM(a.ProcInic5*0.2))) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina5))) / CONVERT(DECIMAL, (SUM(a.ProcInic5*0.2)))
                 END ProcIndi5, 
				 case when CONVERT(DECIMAL, (SUM(a.ProcInic1*0.2) + SUM(a.ProcInic4*0.2) + SUM(a.ProcInic5*0.2))) = 0 then
				 0
				 else
                 CONVERT(DECIMAL, (SUM(a.ProcFina1) + SUM(a.ProcFina4) + SUM(a.ProcFina5))) / CONVERT(DECIMAL, (SUM(a.ProcInic1*0.2) + SUM(a.ProcInic4*0.2) + SUM(a.ProcInic5*0.2))) end ProcIndiTota
          FROM a
               INNER JOIN Seccionales ON Seccionales.SeccionalId = a.SeccionalId
          GROUP BY Seccional
          ORDER BY 1;";

				    // Ejecuta la consulta
    $resultado = CustomQuery($sql);

		// Genera el inicio de la tabla HTML
		$htmlTable = '<div id="miContenedor" style="display: flex; margin-bottom: 20px;">';

		// Agrega el texto
		//$htmlTable .= '<div style="flex: 1; text-align: center; font-weight: bold; font-size: 16px;">';
		$htmlTable .= '<div style="flex: 1;">';
				// Agrega la imagen
		//$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px;">';
		$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px; float: left; margin-right: 20px;">';
		$htmlTable .= '<p style="display: block; text-align: center; font-weight: bold; font-size: 16px; margin-left: 235px;">';
		$htmlTable .= 'Dirección Ejecutiva de Administración Judicial<br>';
		$htmlTable .= 'División de Cobro Coactivo<br>';
	  $htmlTable .= 'Gestión Medidas Cautelares a  '.$ultimo_dia.'<br>';
		$htmlTable .= 'Consolidado por Dirección Seccional<br>';
		$htmlTable .= '</p>';

		// Agrega el título de la tabla
		$htmlTable .= '<table border="1" cellpadding="9" cellspacing="0" style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;">';

		// Estilo de encabezado
		$htmlTable .= '<thead style="background-color: #d9d9d9; font-weight: bold; text-align: center;">';

		$htmlTable .= '<tr>';
		$htmlTable .= '<td rowspan="3" colspan="1" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;  width: 20%;">DIRECCION SECCIONAL</td>';
		$htmlTable .= '<td colspan="4" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA CORRIENTE</td>';
		$htmlTable .= '<td colspan="4" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA MINJUSTICIA</td>';
		$htmlTable .= '<td colspan="4" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA EJEMPLARIZANTE</td>';
		$htmlTable .= '<td colspan="4" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">TOTAL</td>';
		$htmlTable .= '</tr>';
		$htmlTable .= '<tr>';
		$htmlTable .= '<th colspan="2" style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Med. Cautelares sobre productos Bancarios</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Indicadores de gestión medidas</th>';
		$htmlTable .= '<th colspan="2" style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Med. Cautelares sobre productos Bancarios</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Indicadores de gestión medidas</th>';		
		$htmlTable .= '<th colspan="2"style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Med. Cautelares sobre productos Bancarios</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Indicadores de gestión medidas</th>';
		$htmlTable .= '<th colspan="2" style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Med. Cautelares sobre productos Bancarios</th>';
		$htmlTable .= '<th rowspan="2" style="text-align: center; width: 10%;">Indicadores de gestión medidas</th>';
		$htmlTable .= '</tr>';

		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 5%;">100%</th>'; // Primera columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">20%</th>'; // Segunda columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">100%</th>'; // Primera columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">20%</th>'; // Segunda columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">100%</th>'; // Primera columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">20%</th>'; // Segunda columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">100%</th>'; // Primera columna dentro de "Procesos activos"
		$htmlTable .= '<th style="text-align: center; width: 5%;">20%</th>'; // Segunda columna dentro de "Procesos activos"
		$htmlTable .= '</tr>';


		$htmlTable .= '</thead>';

		// Genera el cuerpo de la tabla
		$htmlTable .= '<tbody>';



		// Procesa los resultados y agrega las filas
		while ($data = db_fetch_array($resultado)) {

			 $htmlTable .= '<tr>';
			 $htmlTable .= '<td style="text-align: center;">' . htmlspecialchars($data['Seccional']) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic1'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic120'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina1'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi1']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic4'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic420'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina4'])) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi4']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic5'], 0, ',', '.')) .  '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic520'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina5'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi5']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInicTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInicTota20'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFinaTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndiTota']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '</tr>';
				
				$TotalProcInic1 += $data['ProcInic1'];
				$TotalProcInic120 += $data['ProcInic120'];
				$TotalProcFina1 += $data['ProcFina1'];
				//$TotalProcProcIndi1 += $data['ProcIndi1'];
				$TotalValoProcInic4 += $data['ProcInic4'];
				$TotalValoProcInic420 += $data['ProcInic420'];
				$TotalProcFina4 += $data['ProcFina4'];
				//$TotalProcIndi4 += $data['ProcIndi4'];
				$TotalProcInic5 += $data['ProcInic5'];
				$TotalProcInic520 += $data['ProcInic520'];
				$TotalProcFina5 += $data['ProcFina5'];
				//$TotalProcIndi5 += $data['ProcIndi5'];
				$TotalProcInicTota += $data['ProcInicTota'];
				$TotalProcInicTota20 += $data['ProcInicTota20'];
				$TotalProcFinaTota+= $data['ProcFinaTota'];
				//$TotalProcProcIndiTota += $data['ProcIndiTota'];


				
		}
		
		$TotalProcProcIndi1 = ($TotalProcFina1 / ($TotalProcInic1 * 0.2))*100;
		$TotalProcIndi4 = ($TotalProcFina4 / ($TotalValoProcInic4 * 0.2))*100;
		$TotalProcIndi5 = ($TotalProcFina5 / ($TotalProcInic5 * 0.2))*100;
		$TotalProcProcIndiTota = ($TotalProcFinaTota / ($TotalProcInicTota * 0.2))*100;

		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 20%; bold;">Totales</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic1, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic120, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina1, 0, ',', '.')) . '</th>';
    $htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round($TotalProcProcIndi1 , 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalValoProcInic4, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalValoProcInic420, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina4, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round($TotalProcIndi4, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic5, 0, ',', '.')) . '</th>';
	  $htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic520, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina5, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round($TotalProcIndi5, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInicTota, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInicTota20, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFinaTota, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round($TotalProcProcIndiTota, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '</tr>';

		$htmlTable .= '</tbody>';
		$htmlTable .= '</table>';
		$htmlTable .= '</div>';
		$htmlTable .= '</div>'; // Cierra el div flex


		// Asigna el HTML generado a una variable para usarla en la plantilla
		$xt->assign("mi_tabla_html", $htmlTable);

		return true; // Devuelve true para continuar con el proceso

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>