<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_indicadores_de_b_squeda  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

				

		 $U_user = $_SESSION["UserNameF"];
		 $ejecutivo_hasta = 	$_SESSION['indicadores_busqueda_mes'];// Fecha en formato YYYY-MM-DD

		 // Separar la fecha en año, mes y día
		//list($ano, $mes, $dia) = explode('-', $cons_mes);


		// Crear un objeto DateTime a partir del año y mes
		$dateDesde = new DateTime($ejecutivo_desde);
		$dateHasta = new DateTime($ejecutivo_hasta);

		// Generar el primer día del mes
		$primer_dia = $dateDesde->modify('first day of this month')->format('d-m-Y');

		// Generar el último día del mes
		$ultimo_dia = $dateHasta->modify('last day of this month')->format('d-m-Y');

		// Definir un array con los nombres de las carteras
		$cartera = [
			 '1' => 'CARTERA CORRIENTE',
			 '2' => 'CARTERA PRESCRITA CSJ',
			 '3' => 'CARTERA PRESCRITA MINJUSTICIA',
			 '4' => 'CARTERA MINJUSTICIA',
			 '5' => 'CARTERA EJEMPLARIZANTE'
		];

		// Convertir el id cartera numérico al nombre correspondiente
		$cartera_nombre = $cartera[$ejecutivo_cartera ];


		  global $xt;


  		$sql = "DECLARE  @Hasta DATE = '$ejecutivo_hasta';
     SET @Hasta = EOMONTH(@Hasta);
     WITH a
          AS (
          -- 1 Inicial
          SELECT SeccionalId, 
                 COUNT(*) AS ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
                Hasta = @Hasta
               AND CarteraTipoId = 1
          GROUP BY SeccionalId

          UNION ALL -- 4 Inicial

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 COUNT(*) AS ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
               Hasta = @Hasta
               AND CarteraTipoId = 4
          GROUP BY SeccionalId

          UNION ALL -- 5 Inicial

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 COUNT(*) AS ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE
               Hasta = @Hasta
               AND CarteraTipoId = 5
          GROUP BY SeccionalId

          UNION ALL -- 1 Final

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 COUNT(*) AS ProcFina1, 
                 0 ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 1)
			   --AND (EstadoId = 2)
                   AND NOT EXISTS
              (
                  SELECT Correspondencias.ProcesoId
                  FROM Oficios
                       INNER JOIN Correspondencias ON Oficios.OficioId = Correspondencias.OficioId
                  WHERE(Oficios.ActuacionId = 1035)
                       AND (Correspondencias.Fecha <= @Hasta)
                       AND (Correspondencias.ProcesoId = Historicos.ProcesoId)
              )
          GROUP BY SeccionalId

          UNION ALL -- 4

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 COUNT(*) AS ProcFina4, 
                 0 ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 4)
			   --AND (EstadoId = 2)
                   AND NOT EXISTS
              (
                  SELECT Correspondencias.ProcesoId
                  FROM Oficios
                       INNER JOIN Correspondencias ON Oficios.OficioId = Correspondencias.OficioId
                  WHERE(Oficios.ActuacionId = 1035)
                       AND (Correspondencias.Fecha <= @Hasta)
                       AND (Correspondencias.ProcesoId = Historicos.ProcesoId)
              )
          GROUP BY SeccionalId

          UNION ALL -- 5 Final

          SELECT SeccionalId, 
                 0 ProcInic1, 
                 0 ProcInic4, 
                 0 ProcInic5, 
                 0 ProcFina1, 
                 0 ProcFina4, 
                 COUNT(*) AS ProcFina5
          FROM Historicos
          WHERE(Hasta = @Hasta)
               AND (CarteraTipoId = 5)
			   --AND (EstadoId = 2)
                   AND NOT EXISTS
              (
                  SELECT Correspondencias.ProcesoId
                  FROM Oficios
                       INNER JOIN Correspondencias ON Oficios.OficioId = Correspondencias.OficioId
                  WHERE(Oficios.ActuacionId = 1035)
                       AND (Correspondencias.Fecha <= @Hasta)
                       AND (Correspondencias.ProcesoId = Historicos.ProcesoId)
              )
          GROUP BY SeccionalId
		  )
          SELECT Seccional, 
                 SUM(a.ProcInic1) ProcInic1, 
                 SUM(a.ProcInic4) ProcInic4, 
                 SUM(a.ProcInic5) ProcInic5, 
                 SUM(a.ProcInic1) + SUM(a.ProcInic4) + SUM(a.ProcInic5) ProcInicTota, 
                 SUM(a.ProcFina1) ProcFina1, 
                 SUM(a.ProcFina4) ProcFina4, 
                 SUM(a.ProcFina5) ProcFina5, 
                 SUM(a.ProcFina1) + SUM(a.ProcFina4) + SUM(a.ProcFina5) ProcFinaTota,
                 CASE
                     WHEN SUM(a.ProcInic1) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina1))) / CONVERT(DECIMAL, (SUM(a.ProcInic1)))
                 END ProcIndi1,
                 CASE
                     WHEN SUM(a.ProcInic4) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina4))) / CONVERT(DECIMAL, (SUM(a.ProcInic4)))
                 END ProcIndi4,
                 CASE
                     WHEN SUM(a.ProcInic5) = 0
                     THEN 0
                     ELSE CONVERT(DECIMAL, (SUM(a.ProcFina5))) / CONVERT(DECIMAL, (SUM(a.ProcInic5)))
                 END ProcIndi5, 
                 CONVERT(DECIMAL, (SUM(a.ProcFina1) + SUM(a.ProcFina4) + SUM(a.ProcFina5))) / CONVERT(DECIMAL, (SUM(a.ProcInic1) + SUM(a.ProcInic4) + SUM(a.ProcInic5))) ProcIndiTota
          FROM a
               INNER JOIN Seccionales ON Seccionales.SeccionalId = a.SeccionalId
          GROUP BY Seccional
          ORDER BY 1;";
		    // Define tu consulta SQL

    // Ejecuta la consulta
    $resultado = CustomQuery($sql);

		// Genera el inicio de la tabla HTML
		$htmlTable = '<div id="miContenedor" style="display: flex; margin-bottom: 20px;">';

		// Agrega el texto
		//$htmlTable .= '<div style="flex: 1; text-align: center; font-weight: bold; font-size: 16px;">';
		$htmlTable .= '<div style="flex: 1;">';
				// Agrega la imagen
		//$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px;">';
		$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px; float: left; margin-right: 20px;">';
		$htmlTable .= '<p style="display: block; text-align: center; font-weight: bold; font-size: 16px; margin-left: 235px;">';
		$htmlTable .= 'Dirección Ejecutiva de Administración Judicial<br>';
		$htmlTable .= 'División de Cobro Coactivo<br>';
	  $htmlTable .= 'Indicadores de Gestión Búsquedas de Bienes a '.$ultimo_dia.'<br>';
		$htmlTable .= 'Consolidado por Dirección Seccional<br>';
		$htmlTable .= '</p>';

		// Agrega el título de la tabla
		$htmlTable .= '<table border="1" cellpadding="9" cellspacing="0" style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;">';

		// Estilo de encabezado
		$htmlTable .= '<thead style="background-color: #d9d9d9; font-weight: bold; text-align: center;">';

		$htmlTable .= '<tr>';
		$htmlTable .= '<td rowspan="2" colspan="1" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;  width: 20%;">DIRECCION SECCIONAL</td>';
		$htmlTable .= '<td colspan="3" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA CORRIENTE</td>';
		$htmlTable .= '<td colspan="3" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA MINJUSTICIA</td>';
		$htmlTable .= '<td colspan="3" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA EJEMPLARIZANTE</td>';
		$htmlTable .= '<td colspan="3" style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">TOTAL</td>';
		$htmlTable .= '</tr>';
		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos sin búsqueda de bienes</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Indicadores de gestión búsquedas</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos sin búsqueda de bienes</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Indicadores de gestión búsquedas</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos sin búsqueda de bienes</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Indicadores de gestión búsquedas</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos activos</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Procesos sin búsqueda de bienes</th>';
		$htmlTable .= '<th style="text-align: center; width: 10%;">Indicadores de gestión búsquedas</th>';
		$htmlTable .= '</tr>';
		$htmlTable .= '</thead>';

		// Genera el cuerpo de la tabla
		$htmlTable .= '<tbody>';



		// Procesa los resultados y agrega las filas
		while ($data = db_fetch_array($resultado)) {

			 $htmlTable .= '<tr>';
			 $htmlTable .= '<td style="text-align: center;">' . htmlspecialchars($data['Seccional']) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic1'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina1'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi1']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic4'], 0, ',', '.')) . '</td>';
			 //$htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcFina4'] * 100, 2), 2, ',', '.')) . ' %</td>';
			 //$htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi4'] * 100, 2), 2, ',', '.')) . ' %</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina4'])) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi4']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInic5'])) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFina5'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndi5']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcInicTota'])) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format($data['ProcFinaTota'], 0, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' . htmlspecialchars(number_format(round($data['ProcIndiTota']* 100, 2), 2, ',', '.')) . '%</td>';
			 $htmlTable .= '</tr>';
				
				$TotalProcInic1 += $data['ProcInic1'];
				$TotalProcFina1 += $data['ProcFina1'];
				$TotalProcProcIndi1 += $data['ProcIndi1'];
				$TotalValoProcInic4 += $data['ProcInic4'];
				$TotalProcFina4 += $data['ProcFina4'];
				$TotalProcIndi4 += $data['ProcIndi4'];
				$TotalProcInic5 += $data['ProcInic5'];
				$TotalProcFina5 += $data['ProcFina5'];
				$TotalProcIndi5 += $data['ProcIndi5'];
				$TotalProcInicTota += $data['ProcInicTota'];
				$TotalProcFinaTota+= $data['ProcFinaTota'];
				$TotalProcProcIndiTota += $data['ProcIndiTota'];


				
		}
		
		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 20%; bold;">Totales</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic1, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina1, 0, ',', '.')) . '</th>';
    $htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round(($TotalProcFina1 / $TotalProcInic1) * 100, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalValoProcInic4, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina4, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round(($TotalProcFina4 / $TotalValoProcInic4) * 100, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInic5, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFina5, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round(($TotalProcFina5 / $TotalProcInic5) * 100, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcInicTota, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' . htmlspecialchars(number_format($TotalProcFinaTota, 0, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; font-weight: bold;">' . htmlspecialchars(number_format(round(($TotalProcFinaTota / $TotalProcInicTota) * 100, 2), 2, ',', '.')) . '%</th>';
		$htmlTable .= '</tr>';

		$htmlTable .= '</tbody>';
		$htmlTable .= '</table>';
		$htmlTable .= '</div>';
		$htmlTable .= '</div>'; // Cierra el div flex


		// Asigna el HTML generado a una variable para usarla en la plantilla
		$xt->assign("mi_tabla_html", $htmlTable);

		return true; // Devuelve true para continuar con el proceso
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>