<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_medidas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["ProcessValuesAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		/*
$procesoId=$values['ProcesoId'];
$consulta=DB::Query("SELECT * FROM Procesos WHERE ProcesoId =".$procesoId);
        while( $date = $consulta->fetchAssoc() )
		{
            $sancionadoId=$date["SancionadoId"];
        }
$_SESSION["SancionadoId"]=$sancionadoId;
*/
// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		/*
$data = $button->getCurrentRecord();
$procesoId=$data["ProcesoId"];
//$procesoId=$data['ProcesoId'];
echo "<script>alert('Value".$procesoId."');</script>";
echo "<script>console.log('Value".$procesoId."');</script>";
$consulta=DB::Query("SELECT TOP 1 * FROM Procesos WHERE ProcesoId =".$procesoId);
        while( $date = $consulta->fetchAssoc() )
		{
            $sancionadoId=$date["SancionadoId"];
        }
$_SESSION["SancionadoId"]=$sancionadoId;
*/

;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, $pageObject)
{

		$data = $button->getCurrentRecord();
$procesoId=$values["ProcesoId"];
//$procesoId=$data['ProcesoId'];
echo "<script>alert('Value".$procesoId."');</script>";
echo "<script>console.log('Value".$procesoId."');</script>";
$consulta=DB::Query("SELECT TOP 1 * FROM Procesos WHERE ProcesoId =".$procesoId);
        while( $date = $consulta->fetchAssoc() )
		{
            $sancionadoId=$date["SancionadoId"];
        }
$_SESSION["SancionadoId"]=$sancionadoId;


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>