<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_medidas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessAdd"]=true;


	}

//	handlers

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		    // Verifica si hay un registro maestro disponible
    $data = $pageObject->getMasterRecord();
 
		//echo($data['SancionadoId']);
    if ($data) {
        // Obtiene el ID del sancionado
        $sancionadoId = $data["SancionadoId"];
        // Almacena el ID en la sesión
        $_SESSION['SancionadoId'] = $sancionadoId;
    }

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>