<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_obligaciones_de_dificil_recaudo  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

	set_time_limit(0); // Elimina la restricción de timeout
$username = $_SESSION["UserNameF"];

  $sql = "SELECT TOP (1) 
    [Extent1].[UserId] AS [UserId], 
    [Extent1].[UserName] AS [UserName], 
    [Extent1].[HorarioId] AS [HorarioId], 
    [Extent1].[SeccionalId] AS SeccionalId, 
    [Extent1].[AbogadoId] AS [AbogadoId], 
    [Extent1].[Email] AS [Email], 
    [Extent1].[CarteraTipoId] AS CarteraTipoId, 
    [Extent1].[Fecha] AS [Fecha], 
    [Extent1].[Nombre] AS [Nombre]
    FROM [dbo].[UserProfile] AS [Extent1]
    WHERE [Extent1].[UserName] = '$username'";

// Ejecutar la consulta
$result = DB::Query($sql);

// Obtener el resultado
$row = $result->fetchAssoc();
$cartera = $row['CarteraTipoId'];
$seccional = $row['SeccionalId'];
$_SESSION['cateraid'] = $cartera;
$_SESSION['seccionalid'] = $seccional;

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>