<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pagos1  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;


		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		$values["Registro"]=now();

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		global $pageObject;
$data = $pageObject->getMasterRecord();
$_SESSION["ConceptoId"]= $data["ConceptoId"];
$_SESSION["NaturalezaId"]= $data["NaturalezaId"];

//print_r($pageObject);

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		include_once (getabspath("classes/calcIntereses.php"));

$valor = $values["Pago"];
$procesoId=$values['ProcesoId'];
// Elimina los puntos
$valor_sin_puntos = str_replace('.', '', $valor);
$values["Pago"] = $valor_sin_puntos;
$rs5 = DB::Query("SELECT GETDATE() AS fechaActual,* FROM Procesos WHERE ProcesoId=".$procesoId);
while( $date = $rs5->fetchAssoc() )
{
	$fechaActual=$date["fechaActual"];
	$fechaPlazo=$date["Plazo"];
}
	$timestampE = strtotime($fechaPlazo);
	$timestampA = strtotime($fechaActual);
	$timestampR = strtotime($values["Fecha"]);
		if ($timestampR<$timestampE or $timestampR>$timestampA){
				echo "<script>alert('La fecha de recaudo no puede ser menor a la fecha Plazo y tampoco mayor a la fecha actual')</script>";
				return false;
		}
		else{
		//echo $dato["fechaEjecutoria"];
		//echo $dato["fechaActual"];
		//print_r($values);
		return true;
	}
//return true;    
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		include_once (getabspath("classes/calcIntereses.php"));
$recalcular=new reliquidacion($values["ProcesoId"]);
$recalcular->pagoId($values["PagoId"]);
//echo "El valor del PagoId es:".$values["PagoId"]; 
$recalcular->Calcular(date('Y-m-d'),1);
//$proxy["saved"]=true;
//echo '<script>alert("Se ingresa el recaudo con exito y se reliquida el proceso")</script>'
/*
echo '<script>if (confirm("Registro de recaudos realizado.")) {
    location.reload();
} else {
    // Aquí puedes agregar un código adicional si el usuario hace clic en "Cancelar"
}</script>'
*/

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		//$fechaActual = new DateTime();
$primerDia = new DateTime(); 
$primerDia->modify('first day of this month');
$fechaRegistro= new DateTime($data["Registro"]);
//echo $primerDia->format('Y-m-d')." - ".$fechaRegistro->format('Y-m-d')."<br>";
//echo $fechaActual . " - ".$primerDia."<br>";
if ($fechaRegistro<$primerDia){ 
	//echo "Entro";
  //$record["ChequeoId_css"].='background:yellow';
	$pageObject->hideItem("custom_button2", $recordId);
}
else{
	$pageObject->hideItem("custom_button1", $recordId);
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>