<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pagos1  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["CustomAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		//$values["Fecha"]=now();

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		//print_r($pageObject);

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		include_once (getabspath("classes/pruebaJuan.php"));
$recalcular=new reliquidacion($values["ProcesoId"]);
$recalcular->Calcular();
$arrayFechas=$recalcular->getFechas();
//print_r($arrayFechas);
foreach($arrayFechas as $dato=>$valor){
	if ($dato=="fechaEjecutoria"){
		$date["fechaEjecutoria"]=$valor;
	}
	else if ($dato=="fechaActual"){
		$date["fechaActual"]=$valor;
	}
}
	$timestampE = strtotime($date["fechaEjecutoria"]);
	$timestampA = strtotime($date["fechaActual"]);
	$timestampR = strtotime($values["Fecha"]);
		if ($timestampR<$timestampE or $timestampR>$timestampA){
				echo "<script>alert('La fecha de recaudo no puede ser menor a la fecha Plazo y tampoco mayor a la fecha actual')</script>";
				return false;
		}
		else{
		//echo $dato["fechaEjecutoria"];
		//echo $dato["fechaActual"];
		//print_r($values);
		return true;
	}
//return true;    
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		include_once (getabspath("classes/pruebaJuan.php"));
$recalcular=new reliquidacion($values["ProcesoId"]);
$recalcular->pagoId($values["PagoId"]);
$recalcular->Calcular();
$proxy["saved"]=true;
//echo '<script>alert("Se ingresa el recaudo con exito y se reliquida el proceso")</script>'
/*
echo '<script>if (confirm("Registro de recaudos realizado.")) {
    location.reload();
} else {
    // Aquí puedes agregar un código adicional si el usuario hace clic en "Cancelar"
}</script>'
*/

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>