<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_procesosreasignar  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeQueryList"]=true;

		$this->events["BeforeProcessList"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		//addNotification( "It's time to check your mail", "Mail check", "glyphicon-envelope", "https://mail.google.com", null, null, true );
/*
$_SESSION["AbogadoId"];
$abogadoId=intval($_SESSION["AbogadoId"]);
$consulta=DB::Query("SELECT * from Procesos where AbogadoId=".$abogadoId)." and ";
while( $date = $consulta->fetchAssoc() )
{
	$userId=$date["UserId"];
	$_SESSION["AbogadoId"]=$date["AbogadoId"];
}
*/
/*
echo "<script>Runner.displayPopup( {
     html: '<form action='classes/upload.php' method='POST' enctype='multipart/form-data'><label for='numero'>No. Proceso: &nbsp; </label><input id='numero' name='numero' type='text' value='' readonly>&nbsp;&nbsp;&nbsp;<label for='procesoId'>ProcesoId:&nbsp</label><input id='procesoId' name='procesoId' type='text' value='5' readonly><br><br><br><input type='file' name='archivo[]' id='archivo' accept='.pdf' multiple /><input type='submit' value='Subir'></input></form><br/><button id='openModalBtn'>Ver Archivos</button><br><div id='lista-archivos'></div>',
     header: 'Subir Archivos',
	  width: 800,
	  height: 500
});</script>"
*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$strWhereClause = whereAdd($strWhereClause, "SeccionalId in (".$_SESSION["Seccionales"].")");


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		//echo $_SESSION["AbogadoId"];
//echo "HEllo";
//http://localhost:8086/procesos_list.php?w3=3
//addNotification( "Tiene varios Procesos por Prescribir", "Procesos a Prescribir", "glyphicon-tag", "http://localhost:8086/dbo_procesosprescritos_list.php", null, null, true );
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>