<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_prueba_archivo_plano  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		

// Evento BeforeProcess

// 1. Realiza la consulta SQL para obtener los datos
$sql = "SELECT SeccionalId, Codigo, CiudadId FROM Seccionales";
$rs = CustomQuery($sql);

$sql2 = "SELECT EstadoId, Estado, Tipo FROM Estados";
$rs2 = CustomQuery($sql2);

// 2. Inicializa una variable para almacenar los datos en formato plano (ejemplo CSV con separadores por ';' Y o '|')
$data1 = "SeccionalId;Codigo;CiudadId\n";
$data2 = "EstadoId;Estado;Tipo\n";

// 3. Recorre los resultados de las consultas y forma las líneas de los archivos
while($row = db_fetch_array($rs)) {
    $data1 .= $row['SeccionalId'] . "|" . $row['Codigo'] . "|" . $row['CiudadId'] . "\n";
}

while($row2 = db_fetch_array($rs2)) {
    $data2 .= $row2['EstadoId'] . "|" . $row2['Estado'] . "|" . $row2['Tipo'] . "\n";
}

// 4. Inicia un buffer de salida
ob_start();

// 5. Crear un archivo ZIP en memoria
$zip = new ZipArchive();
$zipFileName = "archivos_planos.zip";

// 6. Abrir el archivo ZIP desde un buffer
if ($zip->open($zipFileName, ZipArchive::CREATE) !== TRUE) {
    die('Error al crear el archivo ZIP.');
}

// Añadir el primer archivo plano
$zip->addFromString("archivo_plano_1.txt", $data1);

// Añadir el segundo archivo plano
$zip->addFromString("archivo_plano_2.txt", $data2);

// Cerrar el archivo ZIP
$zip->close();

// 7. Obtener el contenido del archivo ZIP desde el buffer
$content = file_get_contents($zipFileName);

// 8. Limpiar el buffer de salida
ob_end_clean();

// 9. Forzar la descarga del archivo ZIP
header('Content-Type: application/zip');
header('Content-Disposition: attachment; filename="archivos_planos.zip"');
header('Content-Length: ' . strlen($content));

// 10. Enviar el archivo ZIP para descarga
echo $content;

// 11. Eliminar el archivo temporal
unlink($zipFileName);

exit();


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>