<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_recaudo_por_seccional  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

			  global $xt;
			
			$recaudo_seccional_busqueda_mes = $_SESSION['recaudo_seccional_busqueda_mes'];

			$fecha = $recaudo_seccional_busqueda_mes;

			$fechaformateada = strtotime($fecha);

			$mes = date("m",$fechaformateada );
			
			$ano = date("Y", $fechaformateada);


		// Definir un array con los nombres de los meses
		$lista_mes = [
			 '01' => 'Enero',
			 '02' => 'Febrero',
			 '03' => 'Marzo',
			 '04' => 'Abril',
			 '05' => 'Mayo',
			 '06' => 'Junio',
			 '07' => 'Julio',
			 '08' => 'Agosto',
			 '09' => 'Septiembre',
			 '10' => 'Octubre',
			 '11' => 'Noviembre',
			 '12' => 'Diciembre'
		];

		// Convertir el numero del mes al nombre correspondiente
		$mes_nombre = $lista_mes[$mes];


			

  		$sql = "	 declare @Desde DATE ='$recaudo_seccional_busqueda_mes'
     declare @Ano int = YEAR(@Desde);
     declare @Hasta DATE = EOMONTH(@Desde);
     WITH a
          AS (
			-- Cartera Corriente
			SELECT        
				ProcesosView1.SeccionalId, 
				SUM(Pagos1.PagoObli+Pagos1.PagoCost+Pagos1.PagoInte+Pagos1.PagoMayo+Pagos1.PagoTerm) AS PagoCorr,
				0 as PagoEjem,
				0 as PagoMinj
			FROM            
				Pagos1 INNER JOIN
				ProcesosView1 ON Pagos1.ProcesoId = ProcesosView1.ProcesoId
			WHERE        
				(YEAR(Pagos1.Registro) = @Ano) 
				AND (Pagos1.Registro <= @Hasta) 
				AND (ProcesosView1.CarteraTipoId = 1)
			GROUP BY ProcesosView1.SeccionalId

          UNION ALL -- Cartera Ejemplarizante

			SELECT        
				ProcesosView1.SeccionalId, 
				0 as PagoCorr,
				SUM(Pagos1.PagoObli+Pagos1.PagoCost+Pagos1.PagoInte+Pagos1.PagoMayo+Pagos1.PagoTerm) AS PagoEjem,
				0 as PagoMinj
			FROM            
				Pagos1 INNER JOIN
				ProcesosView1 ON Pagos1.ProcesoId = ProcesosView1.ProcesoId
			WHERE        
				(YEAR(Pagos1.Registro) = @Ano) 
				AND (Pagos1.Registro <= @Hasta) 
				AND (ProcesosView1.CarteraTipoId = 5)
			GROUP BY ProcesosView1.SeccionalId

          UNION ALL -- Cartera Minjusticia

			SELECT        
				ProcesosView1.SeccionalId, 
				0 as PagoCorr,
				0 as PagoEjem,
				SUM(Pagos1.PagoObli+Pagos1.PagoCost+Pagos1.PagoInte+Pagos1.PagoMayo+Pagos1.PagoTerm) AS PagoMinj
			FROM            
				Pagos1 INNER JOIN
				ProcesosView1 ON Pagos1.ProcesoId = ProcesosView1.ProcesoId
			WHERE        
				(YEAR(Pagos1.Registro) = @Ano) 
				AND (Pagos1.Registro <= @Hasta) 
				AND (ProcesosView1.CarteraTipoId = 4)
			GROUP BY ProcesosView1.SeccionalId
		)
          SELECT Seccional, 
                 SUM(a.PagoCorr) RecaCorr, 
                 SUM(a.PagoEjem) RecaEjem, 
                 SUM(a.PagoMinj) RecaMinj, 
                 SUM(a.PagoCorr) + SUM(a.PagoEjem) + SUM(a.PagoMinj) RecaTota
          FROM a inner join Seccionales on Seccionales.SeccionalId = a.SeccionalId
          GROUP BY Seccional
          ORDER BY Seccional;";
		    // Define tu consulta SQL

    // Ejecuta la consulta
    $resultado = CustomQuery($sql);

		// Genera el inicio de la tabla HTML
		$htmlTable = '<div id="miContenedor" style="display: flex; margin-bottom: 20px;">';

		// Agrega el texto
		//$htmlTable .= '<div style="flex: 1; text-align: center; font-weight: bold; font-size: 16px;">';
		$htmlTable .= '<div style="flex: 1;">';
				// Agrega la imagen
		//$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px;">';
		$htmlTable .= '<img src="images/LogoCSJ.png" alt="Logo" style="width: 215px; height: 70px; float: left; margin-right: 20px;">';
		$htmlTable .= '<p style="display: block; text-align: center; font-weight: bold; font-size: 16px; margin-left: 235px;">';
		$htmlTable .= 'Dirección Ejecutiva de Administración Judicial<br>';
		$htmlTable .= 'División de Cobro Coactivo<br>';
	  $htmlTable .= 'Recaudos Totales a '.$mes_nombre.' '.$ano.'<br>';
		$htmlTable .= 'Consolidado por Dirección Seccional<br>';
		$htmlTable .= '</p>';

		// Agrega el título de la tabla
		$htmlTable .= '<table border="1" cellpadding="9" cellspacing="0" style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;">';

		// Estilo de encabezado
		$htmlTable .= '<thead style="background-color: #d9d9d9; font-weight: bold; text-align: center;">';

		$htmlTable .= '<tr>';
		$htmlTable .= '<td style="text-align: center; font-weight: bold;  background-color: #d9d9d9;  width: 20%;">DIRECCION SECCIONAL</td>';
		$htmlTable .= '<td style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA CORRIENTE</td>';
		$htmlTable .= '<td style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA EJEMPLARIZANTE</td>';
		$htmlTable .= '<td style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">CARTERA MINJUSTICIA</td>';
		$htmlTable .= '<td style="text-align: center; font-weight: bold;  background-color: #d9d9d9;">RECAUDO TOTAL</td>';
		$htmlTable .= '</tr>';
		$htmlTable .= '</thead>';

		// Genera el cuerpo de la tabla
		$htmlTable .= '<tbody>';



		// Procesa los resultados y agrega las filas
		while ($data = db_fetch_array($resultado)) {

			 $htmlTable .= '<tr>';
			 $htmlTable .= '<td style="text-align: center;">' . htmlspecialchars($data['Seccional']) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' .'$ '.htmlspecialchars(number_format($data['RecaCorr'], 2, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' .'$ '. htmlspecialchars(number_format($data['RecaEjem'], 2, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' .'$ '. htmlspecialchars(number_format($data['RecaMinj'], 2, ',', '.')) . '</td>';
			 $htmlTable .= '<td style="text-align: right;">' .'$ '. htmlspecialchars(number_format($data['RecaTota'], 2, ',', '.')) . '</td>';
			 $htmlTable .= '</tr>';
				
				$TotalRecaCorr += $data['RecaCorr'];
				$TotalRecaEjem += $data['RecaEjem'];
				$TotalRecaMinj += $data['RecaMinj'];
				$TotalRecaTota += $data['RecaTota'];

				
		}
		
		$htmlTable .= '<tr>';
		$htmlTable .= '<th style="text-align: center; width: 20%; bold;">Totales</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' .'$ '. htmlspecialchars(number_format($TotalRecaCorr, 2, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' .'$ '. htmlspecialchars(number_format($TotalRecaEjem, 2, ',', '.')) . '</th>';
    $htmlTable .= '<th style="text-align: right; width: 10%; bold;">' .'$ '. htmlspecialchars(number_format($TotalRecaMinj, 2, ',', '.')) . '</th>';
		$htmlTable .= '<th style="text-align: right; width: 10%; bold;">' .'$ '. htmlspecialchars(number_format($TotalRecaTota, 2, ',', '.')) . '</th>';

		$htmlTable .= '</tr>';

		$htmlTable .= '</tbody>';
		$htmlTable .= '</table>';
		$htmlTable .= '</div>';
		$htmlTable .= '</div>'; // Cierra el div flex


		// Asigna el HTML generado a una variable para usarla en la plantilla
		$xt->assign("mi_tabla_html", $htmlTable);

		return true; // Devuelve true para continuar con el proceso

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>