<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_sancionados  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["AfterEdit"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$_SESSION["CarcelId"]=$values["Carcel"];
unset($values["Carcel"]);

//print_r($values);




// Place event code here.
// Use "Add Action" button to add code snippets.
return true;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		//print_r($values);
if (!empty($_SESSION["CarcelId"])){
	$rs1 = DB::Query("SELECT * FROM Carceles WHERE CarcelId=".$_SESSION["CarcelId"]);
		while( $data = $rs1->fetchAssoc() )
		{
			$carcel=$data['Carcel'];
			$ciudad=$data['CiudadId'];
			$direccion=$data['Direccion'];
			$telefonos=$data['Telefono'];
		}
	//$rs2=DB::Exec("INSERT INTO Direcciones (SancionadoId,CarcelId,CiudadId,Direccion,Barrio,Telefonos,Activa) VALUES (".$values['SancionadoId'].",".$carcelId.",".$ciudad.",'".$direccion."',NULL,'".$telefonos."',1)");
	$rs2=DB::Exec("INSERT INTO Direcciones (SancionadoId,CarcelId,CiudadId,Direccion,Barrio,Telefonos,Activa) VALUES (".$values['SancionadoId'].",".$_SESSION["CarcelId"].",".$ciudad.",'".$direccion."',NULL,'".$telefonos."',1)");		
if ($rs2) {
			 //echo "La consulta se realizó correctamente.";
		} 
		else {
			 // Hubo un error en la ejecución de la consulta
			 echo "Error al ejecutar la consulta 1: " . DB::LastError();
			 exit();
		}
}

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		$_SESSION["CarcelId"]=$values["Carcel"];
unset($values["Carcel"]);

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		//print_r($values);
if (!empty($_SESSION["CarcelId"])){
	$rs1 = DB::Query("SELECT * FROM Carceles WHERE CarcelId=".$_SESSION["CarcelId"]);
		while( $data = $rs1->fetchAssoc() )
		{
			$carcel=$data['Carcel'];
			$ciudad=$data['CiudadId'];
			$direccion=$data['Direccion'];
			$telefonos=$data['Telefono'];
		}
	//$rs2=DB::Exec("INSERT INTO Direcciones (SancionadoId,CarcelId,CiudadId,Direccion,Barrio,Telefonos,Activa) VALUES (".$values['SancionadoId'].",".$carcelId.",".$ciudad.",'".$direccion."',NULL,'".$telefonos."',1)");
	$rs2=DB::Exec("INSERT INTO Direcciones (SancionadoId,CarcelId,CiudadId,Direccion,Barrio,Telefonos,Activa) VALUES (".$values['SancionadoId'].",".$_SESSION["CarcelId"].",".$ciudad.",'".$direccion."',NULL,'".$telefonos."',1)");		
if ($rs2) {
			 //echo "La consulta se realizó correctamente.";
		} 
		else {
			 // Hubo un error en la ejecución de la consulta
			 echo "Error al ejecutar la consulta 1: " . DB::LastError();
			 exit();
		}
}

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>