<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tablero_de_control_general  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		

		$username = $_SESSION["UserNameF"];

		$sec = CustomQuery("SELECT TOP 1 
    UserId, 
    UserName, 
    HorarioId, 
    SeccionalId, 
    AbogadoId, 
    Email, 
    CarteraTipoId, 
    Fecha, 
    Nombre
		FROM 
    dbo.UserProfile
		WHERE 
    UserName = '$username';");
		 // Obtener las variables de sesión
		

		// Procesar el resultado para obtener el SeccionalId
		if ($row = db_fetch_array($sec)) {
    $_SESSION['tablero_control_seccionalid'] = $row['SeccionalId'];
		} else {
    // Manejar el caso donde no se encuentre el usuario
    $_SESSION['tablero_control_seccionalid'] = null;
		}

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		

    //global $dal;

    $desde = $_SESSION['tablero_control_desdeid'];
    $hasta = $_SESSION['tablero_control_hastaid'];
	  $cartera = $_SESSION['tablero_control_cartera'];

    // Ejecutar la consulta
    $rs = CustomQuery("
        DECLARE @CarteraTipoId INT = '$cartera';
        DECLARE @Desde DATE = '$desde';
        DECLARE @Hasta DATE = '$hasta';

        SELECT TOP 10 
            Seccionales.Seccional,
            Abogados.Abogado,
            Pagos1.Fecha,
            Pagos1.Pago / 1e6 AS Recaudo
        FROM Pagos1
        INNER JOIN Procesos ON Pagos1.ProcesoId = Procesos.ProcesoId
        INNER JOIN Abogados ON Procesos.AbogadoId = Abogados.AbogadoId
        INNER JOIN Seccionales ON Procesos.SeccionalId = Seccionales.SeccionalId
        WHERE (Pagos1.Fecha BETWEEN @Desde AND @Hasta)
        AND (Procesos.CarteraTipoId = @CarteraTipoId)
        ORDER BY Pagos1.Pago DESC;
    ");

    // Generar el HTML de la tabla
    $tableHTML = '<table class="custom-table">
        <thead>
            <tr>
                <th>Seccional</th>
                <th>Abogado</th>
                <th>Fecha</th>
                <th>Recaudo (en millones)</th>
            </tr>
        </thead>
        <tbody>';

    while($record = db_fetch_array($rs)) {
        $tableHTML .= '<tr>';
        $tableHTML .= '<td>' . htmlspecialchars($record['Seccional']) . '</td>';
        $tableHTML .= '<td>' . htmlspecialchars($record['Abogado']) . '</td>';
        $tableHTML .= '<td>' . htmlspecialchars($record['Fecha']) . '</td>';
        $tableHTML .= '<td>' . number_format($record['Recaudo'], 2) . '</td>';
        $tableHTML .= '</tr>';
    }

    $tableHTML .= '</tbody></table>';

    // Asignar el HTML generado al objeto xt
    $xt->assign("pagos_table", $tableHTML);

;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>