<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tablero_de_control_gesti_n  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		//GESTION DE COBRO PERSUASIVO

    $desde = $_SESSION['tablero_control_desdeid'];
    $hasta = $_SESSION['tablero_control_hastaid'];
	  $cartera = $_SESSION['tablero_control_cartera'];
		$seccional = $_SESSION['tablero_control_seccionalid'];

$rs2 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera';
DECLARE @SeccionalId   INT = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

WITH IndicadoresSumados AS (
    SELECT Abogados.Abogado,
           SUM(Indicadores.Nuevos) AS Nuevos,
           SUM(Indicadores.BusquedaDatos) AS BusquedaDatos,
           SUM(Indicadores.Comunicaciones) AS Comunicaciones,
           SUM(Indicadores.Llamadas) AS Llamadas,
           SUM(Indicadores.AcuerdosPago) AS AcuerdosPago,
           SUM(Indicadores.TerminadosPago) AS TerminadosPago,
           GREATEST(SUM(Indicadores.Nuevos), 
                    SUM(Indicadores.BusquedaDatos), 
                    SUM(Indicadores.Comunicaciones), 
                    SUM(Indicadores.Llamadas), 
                    SUM(Indicadores.AcuerdosPago), 
                    SUM(Indicadores.TerminadosPago)) AS ValorMaximo
    FROM Indicadores
    INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
    WHERE Indicadores.Hasta BETWEEN @Desde AND @Hasta
      AND Indicadores.CarteraTipoId = @CarteraTipoId
      AND Indicadores.SeccionalId = @SeccionalId
      AND EtapaId = 1
    GROUP BY Abogados.Abogado
)
SELECT TOP 1 
       Abogado,
       ValorMaximo AS ValorMayor,
       ValorMaximo / 2.0 AS MitadValorMayor
FROM IndicadoresSumados
ORDER BY ValorMaximo DESC;

    ");

$record2 = db_fetch_array($rs2);

$abogado = $record2['Abogado'];
$valorMayor = $record2['ValorMayor'];
$mitadValorMayor = $record2['MitadValorMayor'];

// Calcular el 10% de $valorMayor
$valor10 = $mitadValorMayor * 0.10;
// Calcular el 20% de $valorMayor
$valor20 = $mitadValorMayor * 0.20;

// Calcular el 40% de $valorMayor
$valor40 = $mitadValorMayor * 0.40;
// Calcular el 80% de $valorMayor
$valor80 = $mitadValorMayor * 0.80;


$rs = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

     SELECT Abogados.Abogado,
            SUM(Indicadores.Nuevos) AS Nuevos,
            SUM(Indicadores.BusquedaDatos) AS BusquedaDatos,
            SUM(Indicadores.Comunicaciones) AS Comunicaciones,
            SUM(Indicadores.Llamadas) AS Llamadas,
            SUM(Indicadores.AcuerdosPago) AS AcuerdosPago,
            SUM(Indicadores.TerminadosPago) AS TerminadosPago
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 1
     GROUP BY Abogados.Abogado;
    ");

    // Generar el HTML de la tabla
    $tableHTML = '<table class="custom-table">
        <thead>
            <tr>
                <th>Abogado</th>
                <th>Aperturas</th>
                <th>BusquedaDatos</th>
                <th>Comunicaciones</th>
								 <th>Llamadas</th>
								 <th>AcuerdosPago</th>
								 <th>TerminadosPago</th>
            </tr>
        </thead>
        <tbody>';

while($record = db_fetch_array($rs)) {
    $tableHTML .= '<tr>';
    $tableHTML .= '<td>' . htmlspecialchars($record['Abogado']) . '</td>';

// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio

$style = '';

if ($record['Nuevos'] > $mitadValorMayor) {
    $style = 'background-color: #92f59a;';
} elseif ($record['Nuevos'] < $mitadValorMayor && $record['Nuevos'] > $valor80) {
    $style = 'background-color: #ff6f6f ;';
} elseif ($record['Nuevos'] <= $valor80 && $record['Nuevos'] > $valor40) {
    $style = 'background-color: #ff9f33;';
} elseif ($record['Nuevos'] <= $valor40 && $record['Nuevos'] > $valor20) {
    $style = 'background-color: #ff9f33;';
} elseif ($record['Nuevos'] <= $valor20 && $record['Nuevos'] > $valor10) {
    $style = 'background-color: #ffb16f;';
}

		$tableHTML .= '<td style="' . $style . '">' . htmlspecialchars($record['Nuevos']) . '</td>';

// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
$styleBusquedaDatos = '';

if ($record['BusquedaDatos'] > $mitadValorMayor) {
    $styleBusquedaDatos = 'background-color: #92f59a;';
} elseif ($record['BusquedaDatos'] < $mitadValorMayor && $record['BusquedaDatos'] > $valor80) {
    $styleBusquedaDatos = 'background-color: #ff6f6f ;';
}  elseif ($record['BusquedaDatos'] <= $valor80 && $record['BusquedaDatos'] > $valor40) {
    $styleBusquedaDatos = 'background-color: #ff9f33;';
} elseif ($record['BusquedaDatos'] <= $valor40 && $record['BusquedaDatos'] > $valor20) {
    $styleBusquedaDatos = 'background-color: #ff9f33;';
} elseif ($record['BusquedaDatos'] <= $valor20 && $record['BusquedaDatos'] > $valor10) {
    $styleBusquedaDatos = 'background-color: #ffb16f;';
}

    $tableHTML .= '<td style="' . $styleBusquedaDatos . '">' . htmlspecialchars($record['BusquedaDatos']) . '</td>';

// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
$styleComunicaciones = '';

if ($record['Comunicaciones'] > $mitadValorMayor) {
    $styleComunicaciones = 'background-color: #92f59a;';
} elseif ($record['Comunicaciones'] < $mitadValorMayor && $record['Comunicaciones'] > $valor80) {
    $styleComunicaciones = 'background-color: #ff6f6f ;';
}  elseif ($record['Comunicaciones'] <= $valor80 && $record['Comunicaciones'] > $valor40) {
    $styleComunicaciones = 'background-color: #ff9f33;';
} elseif ($record['Comunicaciones'] <= $valor40 && $record['Comunicaciones'] > $valor20) {
    $styleComunicaciones = 'background-color: #ff9f33;';
} elseif ($record['Comunicaciones'] <= $valor20 && $record['Comunicaciones'] > $valor10) {
    $styleComunicaciones = 'background-color: #ffb16f;';
}


    $tableHTML .= '<td style="' . $styleComunicaciones . '">' . htmlspecialchars($record['Comunicaciones']) . '</td>';

// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
$styleLlamadas = '';

if ($record['Llamadas'] > $mitadValorMayor) {
    $styleLlamadas = 'background-color: #92f59a;';
} elseif ($record['Llamadas'] < $mitadValorMayor && $record['Llamadas'] > $valor80) {
    $styleLlamadas = 'background-color: #ff6f6f ;';
}elseif ($record['Llamadas'] <= $valor80 && $record['Llamadas'] > $valor40) {
    $styleLlamadas = 'background-color: #ff9f33;';
} elseif ($record['Llamadas'] <= $valor40 && $record['Llamadas'] > $valor20) {
    $styleLlamadas = 'background-color: #ff9f33;';
} elseif ($record['Llamadas'] <= $valor20 && $record['Llamadas'] > $valor10) {
    $styleLlamadas = 'background-color: #ffb16f;';
}

    $tableHTML .= '<td style="' . $styleLlamadas . '">' . htmlspecialchars($record['Llamadas']) . '</td>';

// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio

$styleAcuerdosPago = '';

if ($record['AcuerdosPago'] > $mitadValorMayor) {
    $styleAcuerdosPago = 'background-color: #92f59a;';
} elseif ($record['AcuerdosPago'] < $mitadValorMayor && $record['AcuerdosPago'] > $valor80) {
    $styleAcuerdosPago = 'background-color: #ff6f6f;';
} elseif ($record['AcuerdosPago'] <= $valor80 && $record['AcuerdosPago'] > $valor40) {
    $styleAcuerdosPago = 'background-color: #ff9f33;';
} elseif ($record['AcuerdosPago'] <= $valor40 && $record['AcuerdosPago'] > $valor20) {
    $styleAcuerdosPago = 'background-color: #ff9f33;';
} elseif ($record['AcuerdosPago'] <= $valor20 && $record['AcuerdosPago'] > $valor10) {
    $styleAcuerdosPago = 'background-color: #ffb16f;';
}

$tableHTML .= '<td style="' . $styleAcuerdosPago . '">' . htmlspecialchars($record['AcuerdosPago']) . '</td>';


// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
$styleTerminadosPago = '';

if ($record['TerminadosPago'] > $mitadValorMayor) {
    $styleTerminadosPago = 'background-color: #92f59a;';
} elseif ($record['TerminadosPago'] < $mitadValorMayor && $record['TerminadosPago'] > $valor80) {
    $styleTerminadosPago = 'background-color: #ff6f6f ;';
} elseif ($record['TerminadosPago'] <= $valor80 && $record['TerminadosPago'] > $valor40) {
    $styleTerminadosPago = 'background-color: #ff9f33;';
} elseif ($record['TerminadosPago'] <= $valor40 && $record['TerminadosPago'] > $valor20) {
    $styleTerminadosPago = 'background-color: #ff9f33;';
} elseif ($record['TerminadosPago'] <= $valor20 && $record['TerminadosPago'] > $valor10) {
    $styleTerminadosPago = 'background-color: #ffb16f;';
}


    $tableHTML .= '<td style="' . $styleTerminadosPago . '">' . htmlspecialchars($record['TerminadosPago']) . '</td>';
    $tableHTML .= '</tr>';
}

    $tableHTML .= '</tbody></table>';


//GESTION DE COBRO COACTIVO

$rs33 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

    WITH IndicadoresSumados AS (
     SELECT Abogados.Abogado,
            SUM(Indicadores.MandamientosPago) AS MandamientosPago,
            SUM(Indicadores.BusquedaDatos) AS BusquedaDatos,
            SUM(Indicadores.Citaciones) AS Citaciones,
            SUM(Indicadores.NotificacionCorreo) AS NotificacionCorreo,
            SUM(Indicadores.NotificacionEdictos) AS NotificacionEdictos,
            SUM(Indicadores.DespachosComisorios) AS DespachosComisorios,
            SUM(Indicadores.RevocatoriaMandamientosPago) AS RevocatoriaMandamientosPago,
            SUM(Indicadores.AcuerdosPago) AS AcuerdosPago,
			GREATEST( 
                    SUM(Indicadores.MandamientosPago), 
                    SUM(Indicadores.BusquedaDatos), 
                    SUM(Indicadores.Citaciones), 
                    SUM(Indicadores.NotificacionCorreo),
					SUM(Indicadores.NotificacionEdictos),
					SUM(Indicadores.DespachosComisorios),
					SUM(Indicadores.RevocatoriaMandamientosPago),
					SUM(Indicadores.AcuerdosPago)) AS ValorMaximo
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado)
SELECT TOP 1 
       Abogado,
       ValorMaximo AS ValorMayor,
       ValorMaximo / 2.0 AS MitadValorMayor
FROM IndicadoresSumados
ORDER BY ValorMaximo DESC;
");

$record33 = db_fetch_array($rs33);

$abogado = $record33['Abogado'];
$valorMayor33 = $record33['ValorMayor'];
$mitadValorMayor33 = $record33['MitadValorMayor'];

// Calcular el 10% de $valorMayor
$valor3310 = $mitadValorMayor33 * 0.10;
// Calcular el 20% de $valorMayor
$valor3320 = $mitadValorMayor33 * 0.20;
// Calcular el 40% de $valorMayor
$valor3340 = $mitadValorMayor33 * 0.40;
// Calcular el 80% de $valorMayor
$valor3380 = $mitadValorMayor33 * 0.80;



$rs3 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

     SELECT Abogados.Abogado,
            SUM(Indicadores.MandamientosPago) AS MandamientosPago,
            SUM(Indicadores.BusquedaDatos) AS BusquedaDatos,
            SUM(Indicadores.Citaciones) AS Citaciones,
            SUM(Indicadores.NotificacionCorreo) AS NotificacionCorreo,
            SUM(Indicadores.NotificacionEdictos) AS NotificacionEdictos,
            SUM(Indicadores.DespachosComisorios) AS DespachosComisorios,
            SUM(Indicadores.RevocatoriaMandamientosPago) AS RevocatoriaMandamientosPago,
            SUM(Indicadores.AcuerdosPago) AS AcuerdosPago
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado;
");


    // Generar el HTML de la tabla
    $tableHTMLA = '<table class="custom-table">
        <thead>
            <tr>
                <th>Abogado</th>
                <th>MandamientosPago</th>
                <th>BusquedaDatos</th>
                <th>Citaciones</th>
								 <th>NotificacionCorreo</th>
								 <th>NotificacionEdictos</th>
								 <th>DespachosComisorios</th>
								 <th>RevocatoriaMandamientosPago</th>
								 <th>AcuerdosPago</th>
            </tr>
        </thead>
        <tbody>';
while($record2 = db_fetch_array($rs3)) {
    $tableHTMLA .= '<tr>';
		$tableHTMLA .= '<td>' . htmlspecialchars($record2['Abogado']) . '</td>';
						

$styleMandamientosPago = '';

if ($record2['MandamientosPago'] > $mitadValorMayor33) {
    $styleMandamientosPago = 'background-color: #92f59a;';
} elseif ($record2['MandamientosPago'] < $mitadValorMayor33 && $record2['MandamientosPago'] > $valor3380) {
    $styleMandamientosPago = 'background-color: #ff6f6f ;';
} elseif ($record2['MandamientosPago'] <= $valor3380 && $record2['MandamientosPago'] > $valor3340) {
    $styleMandamientosPago = 'background-color: #ff9f33;';
} elseif ($record2['MandamientosPago'] <= $valor3340 && $record2['MandamientosPago'] > $valor3320) {
    $styleMandamientosPago = 'background-color: #ffb16f;';
}elseif ($record2['MandamientosPago'] <= $valor3320 && $record2['MandamientosPago'] > $valor3310) {
    $styleMandamientosPago = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleMandamientosPago . '">' . htmlspecialchars($record2['MandamientosPago']) . '</td>';
    //$tableHTMLA .= '<td>' . htmlspecialchars($record2['MandamientosPago']) . '</td>';

$styleBusquedaDatos = '';

if ($record2['BusquedaDatos'] > $mitadValorMayor33) {
    $styleBusquedaDatos = 'background-color: #92f59a;';
} elseif ($record2['BusquedaDatos'] < $mitadValorMayor33 && $record2['BusquedaDatos'] > $valor3380) {
    $styleBusquedaDatos = 'background-color: #ff6f6f ;';
} elseif ($record2['BusquedaDatos'] <= $valor3380 && $record2['BusquedaDatos'] > $valor3340) {
    $styleBusquedaDatos = 'background-color: #ff9f33;';
} elseif ($record2['BusquedaDatos'] <= $valor3340 && $record2['BusquedaDatos'] > $valor3320) {
    $styleBusquedaDatos = 'background-color: #ffb16f;';
}elseif ($record2['BusquedaDatos'] <= $valor3320 && $record2['BusquedaDatos'] > $valor3310) {
    $styleBusquedaDatos = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleBusquedaDatos . '">' . htmlspecialchars($record2['BusquedaDatos']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['BusquedaDatos']) . '</td>';

		$styleCitaciones = '';

if ($record2['Citaciones'] > $mitadValorMayor33) {
    $styleCitaciones = 'background-color: #92f59a;';
} elseif ($record2['Citaciones'] < $mitadValorMayor33 && $record2['Citaciones'] > $valor3380) {
    $styleCitaciones = 'background-color: #ff6f6f ;';
} elseif ($record2['Citaciones'] <= $valor3380 && $record2['Citaciones'] > $valor3340) {
    $styleCitaciones = 'background-color: #ff9f33;';
} elseif ($record2['Citaciones'] <= $valor3340 && $record2['Citaciones'] > $valor3320) {
    $styleCitaciones = 'background-color: #ffb16f;';
}elseif ($record2['Citaciones'] <= $valor3320 && $record2['Citaciones'] > $valor3310) {
    $styleCitaciones = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleCitaciones	 . '">' . htmlspecialchars($record2['Citaciones']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['Citaciones']) . '</td>';

				$styleNotificacionCorreo = '';

if ($record2['NotificacionCorreo'] > $mitadValorMayor33) {
    $styleNotificacionCorreo = 'background-color: #92f59a;';
} elseif ($record2['NotificacionCorreo'] < $mitadValorMayor33 && $record2['NotificacionCorreo'] > $valor3380) {
    $styleNotificacionCorreo = 'background-color: #ff6f6f ;';
} elseif ($record2['NotificacionCorreo'] <= $valor3380 && $record2['NotificacionCorreo'] > $valor3340) {
    $styleNotificacionCorreo = 'background-color: #ff9f33;';
} elseif ($record2['NotificacionCorreo'] <= $valor3340 && $record2['NotificacionCorreo'] > $valor3320) {
    $styleNotificacionCorreo = 'background-color: #ffb16f;';
}elseif ($record2['NotificacionCorreo'] <= $valor3320 && $record2['NotificacionCorreo'] > $valor3310) {
    $styleNotificacionCorreo = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleNotificacionCorreo . '">' . htmlspecialchars($record2['NotificacionCorreo']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['NotificacionCorreo']) . '</td>';

				$styleNotificacionEdictos = '';

if ($record2['NotificacionEdictos'] > $mitadValorMayor33) {
    $styleNotificacionEdictos = 'background-color: #92f59a;';
} elseif ($record2['NotificacionEdictos'] < $mitadValorMayor33 && $record2['NotificacionEdictos'] > $valor3380) {
    $styleNotificacionEdictos = 'background-color: #ff6f6f ;';
} elseif ($record2['NotificacionEdictos'] <= $valor3380 && $record2['NotificacionEdictos'] > $valor3340) {
    $styleNotificacionEdictos = 'background-color: #ff9f33;';
} elseif ($record2['NotificacionEdictos'] <= $valor3340 && $record2['NotificacionEdictos'] > $valor3320) {
    $styleNotificacionEdictos = 'background-color: #ffb16f;';
}elseif ($record2['NotificacionEdictos'] <= $valor3320 && $record2['NotificacionEdictos'] > $valor3310) {
    $styleNotificacionEdictos = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleNotificacionEdictos . '">' . htmlspecialchars($record2['NotificacionEdictos']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['NotificacionEdictos']) . '</td>';

						$styleDespachosComisorios = '';

if ($record2['DespachosComisorios'] > $mitadValorMayor33) {
    $styleDespachosComisorios = 'background-color: #92f59a;';
} elseif ($record2['DespachosComisorios'] < $mitadValorMayor33 && $record2['DespachosComisorios'] > $valor3380) {
    $styleDespachosComisorios = 'background-color: #ff6f6f ;';
} elseif ($record2['DespachosComisorios'] <= $valor3380 && $record2['DespachosComisorios'] > $valor3340) {
    $styleDespachosComisorios = 'background-color: #ff9f33;';
} elseif ($record2['DespachosComisorios'] <= $valor3340 && $record2['DespachosComisorios'] > $valor3320) {
    $styleDespachosComisorios = 'background-color: #ffb16f;';
}elseif ($record2['DespachosComisorios'] <= $valor3320 && $record2['DespachosComisorios'] > $valor3310) {
    $styleDespachosComisorios = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleNotificacionEdictos . '">' . htmlspecialchars($record2['DespachosComisorios']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['DespachosComisorios']) . '</td>';

								$styleRevocatoriaMandamientosPago = '';

if ($record2['RevocatoriaMandamientosPago'] > $mitadValorMayor33) {
    $styleRevocatoriaMandamientosPago = 'background-color: #92f59a;';
} elseif ($record2['RevocatoriaMandamientosPago'] < $mitadValorMayor33 && $record2['RevocatoriaMandamientosPago'] > $valor3380) {
    $styleRevocatoriaMandamientosPago = 'background-color: #ff6f6f ;';
} elseif ($record2['RevocatoriaMandamientosPago'] <= $valor3380 && $record2['RevocatoriaMandamientosPago'] > $valor3340) {
    $styleRevocatoriaMandamientosPago = 'background-color: #ff9f33;';
} elseif ($record2['RevocatoriaMandamientosPago'] <= $valor3340 && $record2['RevocatoriaMandamientosPago'] > $valor3320) {
    $styleRevocatoriaMandamientosPago = 'background-color: #ffb16f;';
}elseif ($record2['RevocatoriaMandamientosPago'] <= $valor3320 && $record2['RevocatoriaMandamientosPago'] > $valor3310) {
    $styleRevocatoriaMandamientosPago = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleRevocatoriaMandamientosPago . '">' . htmlspecialchars($record2['RevocatoriaMandamientosPago']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['RevocatoriaMandamientosPago']) . '</td>';

										$styleAcuerdosPago = '';

if ($record2['AcuerdosPago'] > $mitadValorMayor33) {
    $styleAcuerdosPago = 'background-color: #92f59a;';
} elseif ($record2['AcuerdosPago'] < $mitadValorMayor33 && $record2['AcuerdosPago'] > $valor3380) {
    $styleAcuerdosPago = 'background-color: #ff6f6f ;';
} elseif ($record2['AcuerdosPago'] <= $valor3380 && $record2['AcuerdosPago'] > $valor3340) {
    $styleAcuerdosPago = 'background-color: #ff9f33;';
} elseif ($record2['AcuerdosPago'] <= $valor3340 && $record2['AcuerdosPago'] > $valor3320) {
    $styleAcuerdosPago = 'background-color: #ffb16f;';
}elseif ($record2['AcuerdosPago'] <= $valor3320 && $record2['AcuerdosPago'] > $valor3310) {
    $styleAcuerdosPago = 'background-color: #ffb16f;';
}
		$tableHTMLA .= '<td style="' . $styleAcuerdosPago . '">' . htmlspecialchars($record2['AcuerdosPago']) . '</td>';

		//$tableHTMLA .= '<td>' . htmlspecialchars($record2['AcuerdosPago']) . '</td>';
    $tableHTMLA .= '</tr>';
}

		$tableHTMLA .= '</tbody></table>';




//GESTION DE COACTIVO EJECUCION

$rs40 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

WITH IndicadoresSumados AS (
 SELECT Abogados.Abogado,
            SUM(Indicadores.IncumplimientoAcuerdosPago) AS IncumplimientoAcuerdosPago,
            SUM(Indicadores.Suspension) AS Suspension,
            SUM(Indicadores.Interrupcion) AS Interrupcion,
            SUM(Indicadores.LevantamientosSI) AS LevantamientosSI,
            SUM(Indicadores.ResuelveExcepciones) AS ResuelveExcepciones,
            SUM(Indicadores.EjecucionLiquidacion) AS EjecucionLiquidacion,
            SUM(Indicadores.RegistroMedidaCautelar) AS RegistroMedidaCautelar,
            SUM(Indicadores.Embargos) AS Embargos,
            SUM(Indicadores.ComunicacionEmbargo) AS ComunicacionEmbargo,
            SUM(Indicadores.SolicitudMedidaCautelar) AS SolicitudMedidaCautelar,
            SUM(Indicadores.NombramientosSecuestres) AS NombramientosSecuestres,
            SUM(Indicadores.NotificacionSecuestres) AS NotificacionSecuestres,
            SUM(Indicadores.Avaluos) AS Avaluos,
            SUM(Indicadores.AvisosRemates) AS AvisosRemates,
            SUM(Indicadores.DiligenciaRemates) AS DiligenciaRemates,
            SUM(Indicadores.ApruebanRemates) AS ApruebanRemates,
            SUM(Indicadores.LevantamientoMedidaCautelar) AS LevantamientoMedidaCautelar,
				    GREATEST(SUM(Indicadores.IncumplimientoAcuerdosPago), 
                    SUM(Indicadores.Suspension), 
                    SUM(Indicadores.Interrupcion), 
                    SUM(Indicadores.LevantamientosSI), 
                    SUM(Indicadores.ResuelveExcepciones),
					SUM(Indicadores.EjecucionLiquidacion),
					SUM(Indicadores.RegistroMedidaCautelar),
					SUM(Indicadores.Embargos),
					SUM(Indicadores.ComunicacionEmbargo),
					SUM(Indicadores.SolicitudMedidaCautelar),
					SUM(Indicadores.NombramientosSecuestres),
					SUM(Indicadores.NotificacionSecuestres),
					SUM(Indicadores.Avaluos),
					SUM(Indicadores.AvisosRemates),
					SUM(Indicadores.DiligenciaRemates),
					SUM(Indicadores.ApruebanRemates),
					SUM(Indicadores.LevantamientoMedidaCautelar)) AS ValorMaximo
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado)
SELECT TOP 1 
       Abogado,
       ValorMaximo AS ValorMayor,
       ValorMaximo / 2.0 AS MitadValorMayor
FROM IndicadoresSumados
ORDER BY ValorMaximo DESC;
");


$record40 = db_fetch_array($rs40);

$abogado = $record40['Abogado'];
$valorMayo_40r = $record40['ValorMayor'];
$mitadValorMayor_40 = $record40['MitadValorMayor'];

// Calcular el 10% de $valorMayor
$valor40_10 = $mitadValorMayor_40 * 0.10;
// Calcular el 20% de $valorMayor
$valor40_20 = $mitadValorMayor_40 * 0.20;
// Calcular el 40% de $valorMayor
$valor40_40 = $mitadValorMayor_40 * 0.40;
// Calcular el 80% de $valorMayor
$valor80_40 = $mitadValorMayor_40 * 0.80;




$rs4 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

     SELECT Abogados.Abogado,
            SUM(Indicadores.IncumplimientoAcuerdosPago) AS IncumplimientoAcuerdosPago,
            SUM(Indicadores.Suspension) AS Suspension,
            SUM(Indicadores.Interrupcion) AS Interrupcion,
            SUM(Indicadores.LevantamientosSI) AS LevantamientosSI,
            SUM(Indicadores.ResuelveExcepciones) AS ResuelveExcepciones,
            SUM(Indicadores.EjecucionLiquidacion) AS EjecucionLiquidacion,
            SUM(Indicadores.RegistroMedidaCautelar) AS RegistroMedidaCautelar,
            SUM(Indicadores.Embargos) AS Embargos,
            SUM(Indicadores.ComunicacionEmbargo) AS ComunicacionEmbargo,
            SUM(Indicadores.SolicitudMedidaCautelar) AS SolicitudMedidaCautelar,
            SUM(Indicadores.NombramientosSecuestres) AS NombramientosSecuestres,
            SUM(Indicadores.NotificacionSecuestres) AS NotificacionSecuestres,
            SUM(Indicadores.Avaluos) AS Avaluos,
            SUM(Indicadores.AvisosRemates) AS AvisosRemates,
            SUM(Indicadores.DiligenciaRemates) AS DiligenciaRemates,
            SUM(Indicadores.ApruebanRemates) AS ApruebanRemates,
            SUM(Indicadores.LevantamientoMedidaCautelar) AS LevantamientoMedidaCautelar
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado;
");


    // Generar el HTML de la tabla
    $tableHTMLB = '<table class="custom-table">
        <thead>
            <tr>
                <th>Abogado</th>
                <th>IncumplimientoAcuerdosPago</th>
                <th>Suspension</th>
                <th>Interrupcion</th>
								 <th>LevantamientosSI</th>
								 <th>ResuelveExcepciones</th>
								 <th>EjecucionLiquidacion</th>
								 <th>RegistroMedidaCautelar</th>
								 <th>Embargos</th>
								 <th>ComunicacionEmbargo</th>
								 <th>SolicitudMedidaCautelar</th>
								 <th>NombramientosSecuestres</th>
								 <th>NotificacionSecuestres</th>
								 <th>Avaluos</th>
								 <th>DiligenciaRemates</th>
								 <th>AvisosRemates</th>
								 <th>ApruebanRemates</th>
								 <th>LevantamientoMedidaCautelar</th>
            </tr>
        </thead>
        <tbody>';
while($record3 = db_fetch_array($rs4)) {
    $tableHTMLB .= '<tr>';
    $tableHTMLB .= '<td>' . htmlspecialchars($record3['Abogado']) . '</td>';

				$styleIncumplimientoAcuerdosPago = '';

if ($record3['IncumplimientoAcuerdosPago'] > $mitadValorMayor_40) {
    $styleIncumplimientoAcuerdosPago = 'background-color: #92f59a;';
} elseif ($record3['IncumplimientoAcuerdosPago'] < $mitadValorMayor_40 && $record3['IncumplimientoAcuerdosPago'] > $valor80_40) {
    $styleIncumplimientoAcuerdosPago = 'background-color: #ff6f6f ;';
} elseif ($record3['IncumplimientoAcuerdosPago'] <= $valor80_40 && $record3['IncumplimientoAcuerdosPago'] > $valor40_40) {
    $styleIncumplimientoAcuerdosPago = 'background-color: #ff9f33;';
} elseif ($record3['IncumplimientoAcuerdosPago'] <= $valor40_40 && $record3['IncumplimientoAcuerdosPago'] > $valor40_20) {
    $styleIncumplimientoAcuerdosPago = 'background-color: #ffb16f;';
} elseif ($record3['IncumplimientoAcuerdosPago'] <= $valor40_20 && $record3['IncumplimientoAcuerdosPago'] >= $valor40_10) {
    $styleIncumplimientoAcuerdosPago = 'background-color: #f9dfc0;';
}
		$tableHTMLB .= '<td style="' . $styleIncumplimientoAcuerdosPago . '">' . htmlspecialchars($record3['IncumplimientoAcuerdosPago']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['IncumplimientoAcuerdosPago']) . '</td>';

				// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
		$styleSuspension = '';

if ($record3['Suspension'] > $mitadValorMayor_40) {
    $styleSuspension = 'background-color: #92f59a;';
} elseif ($record3['Suspension'] < $mitadValorMayor_40 && $record3['Suspension'] > $valor80_40) {
    $styleSuspension = 'background-color: #ff6f6f ;';
} elseif ($record3['Suspension'] <= $valor80_40 && $record3['Suspension'] > $valor40_40) {
    $styleSuspension = 'background-color: #ff9f33;';
} elseif ($record3['Suspension'] <= $valor40_40 && $record3['Suspension'] > $valor40_20) {
    $styleSuspension = 'background-color: #ffb16f;';
} elseif ($record3['Suspension'] <= $valor40_20 && $record3['Suspension'] >= $valor40_10) {
    $styleSuspension = 'background-color: #f9dfc0;';
}
		$tableHTMLB .= '<td style="' . $styleSuspension . '">' . htmlspecialchars($record3['Suspension']) . '</td>';
		
		$tableHTMLB .= '<td>' . htmlspecialchars($record3['Interrupcion']) . '</td>';

						// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
		$styleLevantamientosSI = '';

if ($record3['LevantamientosSI'] > $mitadValorMayor_40) {
    $styleLevantamientosSI = 'background-color: #92f59a;';
} elseif ($record3['LevantamientosSI'] < $mitadValorMayor_40 && $record3['LevantamientosSI'] > $valor80_40) {
    $styleLevantamientosSI = 'background-color: #ff6f6f ;';
} elseif ($record3['LevantamientosSI'] < $valor80_40 && $record3['LevantamientosSI'] > $valor40_40) {
    $styleLevantamientosSI = 'background-color: #ff9f33;';
} elseif ($record3['LevantamientosSI'] <= $valor40_40 && $record3['LevantamientosSI'] > $valor40_20) {
    $styleLevantamientosSI = 'background-color: #ffb16f;';
}	elseif ($record3['LevantamientosSI'] <= $valor40_20 && $record3['LevantamientosSI'] >= $valor40_10) {
    $styleLevantamientosSI = 'background-color: #f9dfc0 ;';
}



		$tableHTMLB .= '<td style="' . $styleLevantamientosSI . '">' . htmlspecialchars($record3['LevantamientosSI']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['LevantamientosSI']) . '</td>';
		
		$styleResuelveExcepciones = '';

if ($record3['ResuelveExcepciones'] > $mitadValorMayor_40) {
    $styleResuelveExcepciones = 'background-color: #92f59a;';
} elseif ($record3['ResuelveExcepciones'] < $mitadValorMayor_40 && $record3['ResuelveExcepciones'] > $valor80_40) {
    $styleResuelveExcepciones = 'background-color: #ff6f6f ;';
} elseif ($record3['ResuelveExcepciones'] <= $valor80_40 && $record3['ResuelveExcepciones'] > $valor40_40) {
    $styleResuelveExcepciones = 'background-color: #ff9f33;';
} elseif ($record3['ResuelveExcepciones'] <= $valor40_40 && $record3['ResuelveExcepciones'] > $valor40_20) {
    $styleResuelveExcepciones = 'background-color: #ffb16f;';
}elseif ($record3['ResuelveExcepciones'] <= $valor40_20 && $record3['ResuelveExcepciones'] >= $valor40_10) {
    $styleResuelveExcepciones = 'background-color: #f9dfc0 ;';
}



		$tableHTMLB .= '<td style="' . $styleResuelveExcepciones . '">' . htmlspecialchars($record3['ResuelveExcepciones']) . '</td>';
		
		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['ResuelveExcepciones']) . '</td>';

				$styleEjecucionLiquidacion = '';

if ($record3['EjecucionLiquidacion'] > $mitadValorMayor_40) {
    $styleEjecucionLiquidacion = 'background-color: #92f59a;';
} elseif ($record3['EjecucionLiquidacion'] < $mitadValorMayor_40 && $record3['EjecucionLiquidacion'] > $valor80_40) {
    $styleEjecucionLiquidacion = 'background-color: #ff6f6f ;';
} elseif ($record3['EjecucionLiquidacion'] <= $valor80_40 && $record3['EjecucionLiquidacion'] > $valor40_40) {
    $styleEjecucionLiquidacion = 'background-color: #ff9f33;';
} elseif ($record3['EjecucionLiquidacion'] <= $valor40_40 && $record3['EjecucionLiquidacion'] > $valor40_20) {
    $styleEjecucionLiquidacion = 'background-color: #ffb16f;';
}elseif ($record3['EjecucionLiquidacion'] <= $valor40_20 && $record3['EjecucionLiquidacion'] >= $valor40_10) {
    $styleEjecucionLiquidacion = 'background-color: #f9dfc0 ;';
}



		$tableHTMLB .= '<td style="' . $styleEjecucionLiquidacion . '">' . htmlspecialchars($record3['EjecucionLiquidacion']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['EjecucionLiquidacion']) . '</td>';

						$styleRegistroMedidaCautelar = '';

if ($record3['RegistroMedidaCautelar'] > $mitadValorMayor_40) {
    $styleRegistroMedidaCautelar = 'background-color: #92f59a;';
} elseif ($record3['RegistroMedidaCautelar'] < $mitadValorMayor_40 && $record3['RegistroMedidaCautelar'] > $valor80_40) {
    $styleRegistroMedidaCautelar = 'background-color: #ff6f6f ;';
} elseif ($record3['RegistroMedidaCautelar'] <= $valor80_40 && $record3['RegistroMedidaCautelar'] > $valor40_40) {
    $styleRegistroMedidaCautelar = 'background-color: #ff9f33;';
} elseif ($record3['RegistroMedidaCautelar'] <= $valor40_40 && $record3['RegistroMedidaCautelar'] > $valor40_20) {
    $styleRegistroMedidaCautelar = 'background-color: #ffb16f;';
} elseif ($record3['RegistroMedidaCautelar'] <= $valor40_20 && $record3['RegistroMedidaCautelar'] >= $valor40_10) {
    $styleRegistroMedidaCautelar = 'background-color: #f9dfc0;';
}



		$tableHTMLB .= '<td style="' . $styleRegistroMedidaCautelar . '">' . htmlspecialchars($record3['RegistroMedidaCautelar']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['RegistroMedidaCautelar']) . '</td>';

				$styleEmbargos = '';

if ($record3['Embargos'] > $mitadValorMayor_40) {
    $styleEmbargos = 'background-color: #92f59a;';
} elseif ($record3['Embargos'] < $mitadValorMayor_40 && $record3['Embargos'] > $valor80_40) {
    $styleEmbargos = 'background-color: #ff6f6f ;';
} elseif ($record3['Embargos'] < $valor80_40 && $record3['Embargos'] > $valor40_40) {
    $styleEmbargos = 'background-color: #ff9f33;';
} elseif ($record3['Embargos'] <= $valor40_40 && $record3['Embargos'] > $valor40_20) {
    $styleEmbargos = 'background-color: #ffb16f;';
} elseif ($record3['Embargos'] <= $valor40_20 && $record3['Embargos'] >= $valor40_10) {
    $styleEmbargos = 'background-color: #f9dfc0;';
}
		$tableHTMLB .= '<td style="' . $styleEmbargos . '">' . htmlspecialchars($record3['Embargos']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['Embargos']) . '</td>';

						$styleComunicacionEmbargo = '';

if ($record3['ComunicacionEmbargo'] > $mitadValorMayor_40) {
    $styleComunicacionEmbargo = 'background-color: #92f59a;';
} elseif ($record3['ComunicacionEmbargo'] < $mitadValorMayor_40 && $record3['ComunicacionEmbargo'] > $valor80_40) {
    $styleComunicacionEmbargo = 'background-color: #ff6f6f ;';
} elseif ($record3['ComunicacionEmbargo'] < $valor80_40 && $record3['ComunicacionEmbargo'] > $valor40_40) {
    $styleComunicacionEmbargo = 'background-color: #ff9f33;';
} elseif ($record3['ComunicacionEmbargo'] <= $valor40_40 && $record3['ComunicacionEmbargo'] > $valor40_20) {
    $styleComunicacionEmbargo = 'background-color: #ffb16f;';
} elseif ($record3['ComunicacionEmbargo'] <= $valor40_20 && $record3['ComunicacionEmbargo'] >= $valor40_10) {
    $styleComunicacionEmbargo = 'background-color: #f9dfc0;';
}
		$tableHTMLB .= '<td style="' . $styleComunicacionEmbargo. '">' . htmlspecialchars($record3['ComunicacionEmbargo']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['ComunicacionEmbargo']) . '</td>';

							$styleSolicitudMedidaCautelar = '';

if ($record3['SolicitudMedidaCautelar'] > $mitadValorMayor_40) {
    $styleSolicitudMedidaCautelar = 'background-color: #92f59a;';
} elseif ($record3['SolicitudMedidaCautelar'] < $mitadValorMayor_40 && $record3['SolicitudMedidaCautelar'] > $valor80_40) {
    $styleSolicitudMedidaCautelar = 'background-color: #ff6f6f ;';
} elseif ($record3['SolicitudMedidaCautelar'] <= $valor80_40 && $record3['SolicitudMedidaCautelar'] > $valor40_40) {
    $styleSolicitudMedidaCautelar = 'background-color: #ff9f33;';
} elseif ($record3['SolicitudMedidaCautelar'] <= $valor40_40 && $record3['SolicitudMedidaCautelar'] > $valor40_20) {
    $styleSolicitudMedidaCautelar = 'background-color: #ffb16f;';
} elseif ($record3['SolicitudMedidaCautelar'] <= $valor40_20 && $record3['SolicitudMedidaCautelar'] >= $valor40_10) {
    $styleSolicitudMedidaCautelar = 'background-color: #f9dfc0;';
}
		$tableHTMLB .= '<td style="' . $styleSolicitudMedidaCautelar. '">' . htmlspecialchars($record3['SolicitudMedidaCautelar']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['SolicitudMedidaCautelar']) . '</td>';

							$styleNombramientosSecuestres = '';

if ($record3['NombramientosSecuestres'] > $mitadValorMayor_40) {
    $styleNombramientosSecuestres = 'background-color: #92f59a;';
} elseif ($record3['NombramientosSecuestres'] < $mitadValorMayor_40 && $record3['NombramientosSecuestres'] > $valor80_40) {
    $styleNombramientosSecuestres = 'background-color: #ff6f6f ;';
} elseif ($record3['NombramientosSecuestres'] <= $valor80_40 && $record3['NombramientosSecuestres'] > $valor40_40) {
    $styleNombramientosSecuestres = 'background-color: #ff9f33;';
} elseif ($record3['NombramientosSecuestres'] <= $valor40_40 && $record3['NombramientosSecuestres'] > $valor40_20) {
    $styleNombramientosSecuestres = 'background-color: #ffb16f;';
} elseif ($record3['NombramientosSecuestres'] <= $valor40_20 && $record3['NombramientosSecuestres'] >= $valor40_10) {
    $styleNombramientosSecuestres = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleNombramientosSecuestres. '">' . htmlspecialchars($record3['NombramientosSecuestres']) . '</td>';
		
//$tableHTMLB .= '<td>' . htmlspecialchars($record3['NombramientosSecuestres']) . '</td>';

							$styleNotificacionSecuestres = '';

if ($record3['NotificacionSecuestres'] > $mitadValorMayor_40) {
    $styleNotificacionSecuestres = 'background-color: #92f59a;';
} elseif ($record3['NotificacionSecuestres'] < $mitadValorMayor_40 && $record3['NotificacionSecuestres'] > $valor80_40) {
    $styleNotificacionSecuestres = 'background-color: #ff6f6f ;';
} elseif ($record3['NotificacionSecuestres'] <= $valor80_40 && $record3['NotificacionSecuestres'] > $valor40_40) {
    $styleNotificacionSecuestres = 'background-color: #ff9f33;';
} elseif ($record3['NotificacionSecuestres'] <= $valor40_40 && $record3['NotificacionSecuestres'] > $valor40_20) {
    $styleNotificacionSecuestres = 'background-color: #ffb16f;';
} elseif ($record3['NotificacionSecuestres'] <= $valor40_20 && $record3['NotificacionSecuestres'] >= $valor40_10) {
    $styleNotificacionSecuestres = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleNotificacionSecuestres. '">' . htmlspecialchars($record3['NotificacionSecuestres']) . '</td>';
		
		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['NotificacionSecuestres']) . '</td>';

									$styleAvaluos= '';

if ($record3['Avaluos'] > $mitadValorMayor_40) {
    $styleAvaluos = 'background-color: #92f59a;';
} elseif ($record3['Avaluos'] < $mitadValorMayor_40 && $record3['Avaluos'] > $valor80_40) {
    $styleAvaluos = 'background-color: #ff6f6f ;';
} elseif ($record3['Avaluos'] <= $valor80_40 && $record3['Avaluos'] > $valor40_40) {
    $styleAvaluos = 'background-color: #ff9f33;';
} elseif ($record3['Avaluos'] <= $valor40_40 && $record3['Avaluos'] > $valor40_20) {
    $styleAvaluos = 'background-color: #ffb16f;';
} elseif ($record3['Avaluos'] <= $valor40_20 && $record3['Avaluos'] >= $valor40_10) {
    $styleAvaluos = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleAvaluos. '">' . htmlspecialchars($record3['Avaluos']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['Avaluos']) . '</td>';

											$styleDiligenciaRemates= '';

if ($record3['DiligenciaRemates'] > $mitadValorMayor_40) {
    $styleDiligenciaRemates = 'background-color: #92f59a;';
} elseif ($record3['DiligenciaRemates'] < $mitadValorMayor_40 && $record3['DiligenciaRemates'] > $valor80_40) {
    $styleDiligenciaRemates = 'background-color: #ff6f6f ;';
} elseif ($record3['DiligenciaRemates'] <= $valor80_40 && $record3['DiligenciaRemates'] > $valor40_40) {
    $styleDiligenciaRemates = 'background-color: #ff9f33;';
} elseif ($record3['DiligenciaRemates'] <= $valor40_40 && $record3['DiligenciaRemates'] > $valor40_20) {
    $styleDiligenciaRemates = 'background-color: #ffb16f;';
} elseif ($record3['DiligenciaRemates'] <= $valor40_20 && $record3['DiligenciaRemates'] >= $valor40_10) {
    $styleDiligenciaRemates = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleDiligenciaRemates. '">' . htmlspecialchars($record3['DiligenciaRemates']) . '</td>';
		
		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['DiligenciaRemates']) . '</td>';

											$styleAvisosRemates= '';

if ($record3['AvisosRemates'] > $mitadValorMayor_40) {
    $styleAvisosRemates = 'background-color: #92f59a;';
} elseif ($record3['AvisosRemates'] < $mitadValorMayor_40 && $record3['AvisosRemates'] > $valor80_40) {
    $styleAvisosRemates = 'background-color: #ff6f6f ;';
} elseif ($record3['AvisosRemates'] <= $valor80_40 && $record3['AvisosRemates'] > $valor40_40) {
    $styleAvisosRemates = 'background-color: #ff9f33;';
} elseif ($record3['AvisosRemates'] <= $valor40_40 && $record3['AvisosRemates'] > $valor40_20) {
    $styleAvisosRemates = 'background-color: #ffb16f;';
} elseif ($record3['AvisosRemates'] <= $valor40_20 && $record3['AvisosRemates'] >= $valor40_10) {
    $styleAvisosRemates = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleAvisosRemates. '">' . htmlspecialchars($record3['AvisosRemates']) . '</td>';
		

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['AvisosRemates']) . '</td>';

											$styleApruebanRemates= '';

if ($record3['ApruebanRemates'] > $mitadValorMayor_40) {
    $styleApruebanRemates = 'background-color: #92f59a;';
} elseif ($record3['ApruebanRemates'] < $mitadValorMayor_40 && $record3['ApruebanRemates'] > $valor80_40) {
    $styleApruebanRemates = 'background-color: #ff6f6f ;';
} elseif ($record3['ApruebanRemates'] <= $valor80_40 && $record3['ApruebanRemates'] > $valor40_40) {
    $styleApruebanRemates = 'background-color: #ff9f33;';
} elseif ($record3['ApruebanRemates'] <= $valor40_40 && $record3['ApruebanRemates'] > $valor40_20) {
    $styleApruebanRemates = 'background-color: #ffb16f;';
} elseif ($record3['ApruebanRemates'] <= $valor40_20 && $record3['ApruebanRemates'] >= $valor40_10) {
    $styleApruebanRemates = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleApruebanRemates. '">' . htmlspecialchars($record3['ApruebanRemates']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['ApruebanRemates']) . '</td>';

											$styleLevantamientoMedidaCautelar= '';

if ($record3['LevantamientoMedidaCautelar'] > $mitadValorMayor_40) {
    $styleLevantamientoMedidaCautelar = 'background-color: #92f59a;';
} elseif ($record3['LevantamientoMedidaCautelar'] < $mitadValorMayor_40 && $record3['LevantamientoMedidaCautelar'] > $valor80_40) {
    $styleLevantamientoMedidaCautelar = 'background-color: #ff6f6f ;';
} elseif ($record3['LevantamientoMedidaCautelar'] <= $valor80_40 && $record3['LevantamientoMedidaCautelar'] > $valor40_40) {
    $styleLevantamientoMedidaCautelar = 'background-color: #ff9f33;';
} elseif ($record3['LevantamientoMedidaCautelar'] <= $valor40_40 && $record3['LevantamientoMedidaCautelar'] > $valor40_20) {
    $styleLevantamientoMedidaCautelar = 'background-color: #ffb16f;';
} elseif ($record3['LevantamientoMedidaCautelar'] <= $valor40_20 && $record3['LevantamientoMedidaCautelar'] >= $valor40_10) {
    $styleLevantamientoMedidaCautelar = 'background-color: #f9dfc0;';
}

$tableHTMLB .= '<td style="' . $styleLevantamientoMedidaCautelar. '">' . htmlspecialchars($record3['LevantamientoMedidaCautelar']) . '</td>';

		//$tableHTMLB .= '<td>' . htmlspecialchars($record3['LevantamientoMedidaCautelar']) . '</td>';
		
    $tableHTMLB .= '</tr>';
}

		$tableHTMLB .= '</tbody></table>';


//GESTION DE COACTIVO TERMINACION

$rs50 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

WITH IndicadoresSumados AS (
	      SELECT Abogados.Abogado,
            SUM(Indicadores.Remisibilidad) AS Remisibilidad,
            SUM(Indicadores.PresuncionPrescripcion) AS PresuncionPrescripcion,
            SUM(Indicadores.TerminadosSinPago) AS TerminadosSinPago,
            SUM(Indicadores.Prescritos) AS Prescritos,
            SUM(Indicadores.TerminadosPago) AS TerminadosPago,
			           GREATEST(SUM(Indicadores.Remisibilidad), 
                    SUM(Indicadores.PresuncionPrescripcion), 
                    SUM(Indicadores.TerminadosSinPago), 
                    SUM(Indicadores.Prescritos), 
                    SUM(Indicadores.TerminadosPago)) AS ValorMaximo
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado)
SELECT TOP 1 
       Abogado,
       ValorMaximo AS ValorMayor,
       ValorMaximo / 2.0 AS MitadValorMayor
FROM IndicadoresSumados
ORDER BY ValorMaximo DESC;
");


$record50 = db_fetch_array($rs50);

$abogado = $record50['Abogado'];
$valorMayo_50r = $record50['ValorMayor'];
$mitadValorMayor_50 = $record50['MitadValorMayor'];


// Calcular el 10% de $valorMayor
$valor10_50 = $mitadValorMayor_50 * 0.10;
// Calcular el 20% de $valorMayor
$valor20_50 = $mitadValorMayor_50 * 0.20;

// Calcular el 40% de $valorMayor
$valor40_50 = $mitadValorMayor_50 * 0.40;
// Calcular el 80% de $valorMayor
$valor80_50 = $mitadValorMayor_50 * 0.80;




$rs5 = CustomQuery("DECLARE @CarteraTipoId INT = '$cartera ';
DECLARE @SeccionalId   INT      = '$seccional';
DECLARE @Desde         DATE = '$desde';
DECLARE @Hasta         DATE = '$hasta';

     SELECT Abogados.Abogado,
            SUM(Indicadores.Remisibilidad) AS Remisibilidad,
            SUM(Indicadores.PresuncionPrescripcion) AS PresuncionPrescripcion,
            SUM(Indicadores.TerminadosSinPago) AS TerminadosSinPago,
            SUM(Indicadores.Prescritos) AS Prescritos,
            SUM(Indicadores.TerminadosPago) AS TerminadosPago
     FROM Indicadores
          INNER JOIN Abogados ON Indicadores.AbogadoId = Abogados.AbogadoId
     WHERE(Indicadores.Hasta BETWEEN @Desde AND @Hasta)
          AND (Indicadores.CarteraTipoId = @CarteraTipoId)
          AND (Indicadores.SeccionalId = @SeccionalId) and EtapaId = 2
     GROUP BY Abogados.Abogado;
");


    // Generar el HTML de la tabla
    $tableHTMLC = '<table class="custom-table">
        <thead>
            <tr>
                <th>Abogado</th>
                <th>Remisibilidad</th>
                <th>PresuncionPrescripcion</th>
                <th>TerminadosSinPago</th>
								 <th>Prescritos</th>
								 <th>TerminadosPago</th>
            </tr>
        </thead>
        <tbody>';
while($record5 = db_fetch_array($rs5)) {
    $tableHTMLC .= '<tr>';

		$tableHTMLC .= '<td>' . htmlspecialchars($record5['Abogado']) . '</td>';
		// Condicional para aplicar un estilo en línea si 'Nuevos' es mayor o menor a Medio
		$styleRemisibilidad = '';

if ($record5['Remisibilidad'] > $mitadValorMayor_50) {
    $styleRemisibilidad = 'background-color: #92f59a;';
} elseif ($record5['Remisibilidad'] < $mitadValorMayor_50 && $record5['Remisibilidad'] > $valor80_50) {
    $styleRemisibilidad = 'background-color: #ff6f6f ;';
} elseif ($record5['Remisibilidad'] <= $valor80_50 && $record5['Remisibilidad'] > $valor40_50) {
    $styleRemisibilidad = 'background-color: #ff9f33;';
} elseif ($record5['Remisibilidad'] <= $valor40_50 && $record5['Remisibilidad'] > $valor20_50) {
    $styleRemisibilidad = 'background-color: #ffb16f;';
} elseif ($record5['Remisibilidad'] <= $valor20_50 && $record5['Remisibilidad'] >= $valor10_50) {
    $styleRemisibilidad = 'background-color: #f9dfc0;';
}


		$tableHTMLC .= '<td style="' . $styleRemisibilidad . '">' . htmlspecialchars($record5['Remisibilidad']) . '</td>';

		$stylePresuncionPrescripcion = '';

if ($record5['PresuncionPrescripcion'] > $mitadValorMayor_50) {
    $stylePresuncionPrescripcion = 'background-color: #92f59a;';
} elseif ($record5['PresuncionPrescripcion'] < $mitadValorMayor_50 && $record5['PresuncionPrescripcion'] > $valor80_50) {
    $stylePresuncionPrescripcion = 'background-color: #ff6f6f ;';
} elseif ($record5['PresuncionPrescripcion'] <= $valor80_50 && $record5['PresuncionPrescripcion'] > $valor40_50) {
    $stylePresuncionPrescripcion = 'background-color: #ff9f33;';
} elseif ($record5['PresuncionPrescripcion'] <= $valor40_50 && $record5['PresuncionPrescripcion'] > $valor20_50) {
    $stylePresuncionPrescripcion = 'background-color: #ffb16f;';
} elseif ($record5['PresuncionPrescripcion'] <= $valor20_50 && $record5['PresuncionPrescripcion'] >= $valor10_50) {
    $stylePresuncionPrescripcion = 'background-color: #f9dfc0;';
}


		$tableHTMLC .= '<td style="' . $stylePresuncionPrescripcion . '">' . htmlspecialchars($record5['PresuncionPrescripcion']) . '</td>';



		$styleTerminadosSinPago = '';

if ($record5['TerminadosSinPago'] > $mitadValorMayor_50) {
    $styleTerminadosSinPago = 'background-color: #92f59a;';
} elseif ($record5['TerminadosSinPago'] < $mitadValorMayor_50 && $record5['TerminadosSinPago'] > $valor80_50) {
    $styleTerminadosSinPago = 'background-color: #ff6f6f ;';
} elseif ($record5['TerminadosSinPago'] <= $valor80_50 && $record5['TerminadosSinPago'] > $valor40_50) {
    $styleTerminadosSinPago = 'background-color: #ff9f33;';
} elseif ($record5['TerminadosSinPago'] <= $valor40_50 && $record5['TerminadosSinPago'] > $valor20_50) {
    $styleTerminadosSinPago = 'background-color: #ffb16f;';
} elseif ($record5['TerminadosSinPago'] <= $valor20_50 && $record5['TerminadosSinPago'] >= $valor10_50) {
    $styleTerminadosSinPago = 'background-color: #f9dfc0;';
}

		$tableHTMLC .= '<td style="' . $styleTerminadosSinPago . '">' . htmlspecialchars($record5['TerminadosSinPago']) . '</td>';

		$stylePrescritos = '';

if ($record5['Prescritos'] > $mitadValorMayor_50) {
    $stylePrescritos = 'background-color: #92f59a;';
} elseif ($record5['Prescritos'] < $mitadValorMayor_50 && $record5['Prescritos'] > $valor80_50) {
    $stylePrescritos = 'background-color: #ff6f6f ;';
} elseif ($record5['Prescritos'] <= $valor80_50 && $record5['Prescritos'] > $valor40_50) {
    $stylePrescritos = 'background-color: #ff9f33;';
} elseif ($record5['Prescritos'] <= $valor40_50 && $record5['Prescritos'] > $valor20_50) {
    $stylePrescritos = 'background-color: #ffb16f;';
} elseif ($record5['Prescritos'] <= $valor20_50 && $record5['Prescritos'] >= $valor10_50) {
    $stylePrescritos = 'background-color: #f9dfc0;';
}


		$tableHTMLC .= '<td style="' . $stylePrescritos . '">' . htmlspecialchars($record5['Prescritos']) . '</td>';

		$styleTerminadosPago = '';

if ($record5['TerminadosPago'] > $mitadValorMayor_50) {
    $styleTerminadosPago = 'background-color: #92f59a;';
} elseif ($record5['TerminadosPago'] < $mitadValorMayor_50 && $record5['TerminadosPago'] > $valor80_50) {
    $styleTerminadosPago = 'background-color: #ff6f6f ;';
} elseif ($record5['TerminadosPago'] <= $valor80_50 && $record5['TerminadosPago'] > $valor40_50) {
    $styleTerminadosPago = 'background-color: #ff9f33;';
} elseif ($record5['TerminadosPago'] <= $valor40_50 && $record5['TerminadosPago'] > $valor20_50) {
    $styleTerminadosPago = 'background-color: #ffb16f;';
} elseif ($record5['TerminadosPago'] <= $valor20_50 && $record5['TerminadosPago'] >= $valor10_50) {
    $styleTerminadosPago = 'background-color: #f9dfc0;';
}


		$tableHTMLC .= '<td style="' . $styleTerminadosPago . '">' . htmlspecialchars($record5['TerminadosPago']) . '</td>';

		//$tableHTMLC .= '<td>' . htmlspecialchars($record5['TerminadosPago']) . '</td>';
    $tableHTMLC .= '</tr>';
}

		$tableHTMLC .= '</tbody></table>';



// Asignar el HTML generado al objeto xt
$xt->assign("pagos_table", $tableHTML);
$xt->assign("table_coactivo", $tableHTMLA);
$xt->assign("table_coactivo_ejecucion", $tableHTMLB);
$xt->assign("table_terminacion", $tableHTMLC);


;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>