<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tiposdocumentos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeDelete"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, $pageObject)
{

		
$Documentoid = $deleted_values["TipoDocumentoId"];


if (!$Documentoid) {
    echo "Error: No se recibió TipoDocumentoId correctamente.";
    return;
}

$sql = "SELECT TipoDocumentoId FROM ChequeosSancionados WHERE TipoDocumentoId = '$Documentoid'";
$resultado = CustomQuery($sql);

if ($resultado) {
    if ($fila = db_fetch_array($resultado)) {
        header("Location: tiposdocumentos_list.php?error=1");
        exit();
        //die(); // Detener la ejecución
				
    } else {
        echo "No se encontró tipo de documento con ID: " . $Documentoid;
				header("Location: tiposdocumentos_list.php?succes=1");
				return true;
    }
} else {
    echo "Error en la consulta SQL: " . $sql;
}


;
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>