<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_transacciones_usuario  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

			$sql = "select UserId from UserProfile where UserName = '$username'";
	
	$resultado = CustomQuery($sql);

			// Obtener el valor de reset_date
			if ($data = db_fetch_array($resultado)) {
				 $UserId = $data["UserId"];
			} else {
				 $UserId = null; // Asegurarse de que tenga un valor nulo en caso de error
			}

	$_SESSION['UserId'] = $UserId;

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>