<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_usugcc_ugmembers  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeDelete"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, $pageObject)
{

		    $data = $pageObject->getMasterRecord();
    
    if ($data) {
        // Obtiene el ID del sancionado
        $usuario = $data["username"];
        
    }

		$rolid = $deleted_values['GroupID'];

		//$sqlInsert = "INSERT INTO otra_tabla (campo1, campo2) VALUES ('$campo1', '$campo2')";
		$sqlInsert = "DELETE FROM [UsuGCC-ugmembers] where username = '$usuario' and GroupID = '$rolid'";

 // Enviar un mensaje personalizado al cliente
    
    try {
        CustomQuery($sqlInsert);
        LogInfo("Inserción exitosa: " . $sqlInsert);
    } catch (Exception $e) {
        LogInfo("Error en la inserción: " . $e->getMessage());
    }

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>